### ISSUE TITLE
Generalizing pubsub distribution

### ISSUE THREAD

**Issue by memeplex** [nanomsg/nanomsg#573] opened 2015-12-13 02:42 UTC
pubsub specifies and implements the only built-in subscription based routing mechanism of nanomsg (and zmq). It could be replicated user-side by means of other sps (pushpull is close to the internal pipes of nanomsg/zmq, and nanomsg also offers a protocol api that can directly deal with pipes). But doing it right is no trivial task.

Anyway, why would someone reimplement the sp? Because there are other ways of distributing besides "drop msg if pipe is full". True, the provided one is simple and sensible for the main use case: distribution to many unknown, unreliable, maybe slow subscribers. But the question of blocking when pipe is full pops up every once in a while in stackoverflow and zmq's mailing list. There is even a patch for zmq that implements that, although not without problems [1], [2]. I think even Martin Sustrik suggested a couple of years ago a mechanism to put some back pressure on the publisher.

I think there is a tension between the distribution aspect of pubsub (namely, the send method of dist) and the subscription and routing aspects. Some use cases require these last ones but with a different distribution strategy (v.g. "block if pipe is full", which is a suboptimal but trivial form of flow control, there are other choices here... "send anything you can before sndtimeo"). The current implementation couples the distribution aspect too tight with subscription and routing. One way out of this is to provide socket options for different dist strategies (say PUB_NO_DROP). A more general solution is to have a distbase, in a more OO fashion, so that distribution could be extended the same as protocols and transports, by "overriding the send method".

What do you think?

[1] https://github.com/zeromq/libzmq/issues/1597 
[2] https://github.com/zeromq/libzmq/issues/1598

**Comment by gdamore** [comment] 2015-12-17 02:00
I think you are trying to make nanomsg something it isn't.  Blocking if full vs. available is simply not reasonable to do with pub/sub or *any* multicast type network -- because it means a slow consumer can prevent timely delivery to other consumers.

I'm pretty opposed to such approaches. 

If you have some other need for reliable delivery, then you really shouldn't be using pub/sub.  req/rep is ideal for that use case.

Extending this to provide history, and optional playback for multiple subscribers is interesting, but out of scope for nanomsg -- though such a true MQ could be built using the SP protocols using libnanomsg.  But no single one of these SP patterns in libnanomsg is appropriate on its own -- you'd probably want/need multiple.

**Comment by gdamore** [comment] 2015-12-17 02:00
I'm going to close this -- desired functionality is out of libnanomsg scope.

**Closed by gdamore** 2015-12-17 02:00 UTC

**Comment by memeplex** [comment] 2015-12-17 02:07
Fine, but the point was decoupling routing and sending, not providing history or playback at all! I've detailed my point if view in the mailing list together with a relatively simple change (not too different of what zmq already has implemented). I would have liked to discuss it a bit more. Martin recognized a valid use case but I'm not sure if this issue would be the right one.

**Comment by memeplex** [comment] 2015-12-17 02:10
Btw reqrep is missing the topic routing part, so I'm forced to implement it on top of reqrep or pushpull, so it's not that ideal, that was more or less the entire point, but I don't want too repeat myself here, I've already written too much in the list :)

**Comment by gdamore** [comment] 2015-12-17 02:16
So I'm confused what it is that you're trying to achieve here.  Why do you want to "decouple" these?  Routing is intrinsic to sending. 

Give me a better description of what it is you actually want to achieve, and we can discuss if its appropriate for libnanomsg. 

libzmq has taken the approach of trying to be the answer to all problems anyone has.  It suffers as a result, and that approach is part of why libnanomsg exists.  libnanomsg is a messaging library for a set of well known and common patterns.  If you've got a pattern that fits within the scope, but isn't well represented by the existing code, we can certainly discuss.

Traditional pub/sub is always best effort; its not a message queue.  Maybe that's part of the disconnect?

**Comment by memeplex** [comment] 2015-12-17 02:22
There was a large exchange in the mailing list, I've written a couple of long posts there. The main point was to provide a gauge on confidence and risk aversion of the sender regarding reliability of the receivers by means of a timeout, as a general mechanism defaulting to fully unrealiable in the cases of pub and rep, and to fully reliable in other kind of sockets. I will be glad if you read the posts.

**Comment by gdamore** [comment] 2015-12-17 07:04
I don't recall anything recent to the nanomsg list about this.  How long ago did you post?

You still didn't provide a real answer to what I asked for which was a use case.  Tell me what you need to achieve not how you think you want to achieve it. 

My instinct here is that tunable levels of delivery "effort" are mostly meaningless. Only req/rep can offer a guarantee and that is because there is an ack that is initiated by the app (rep). No other guarantees actually mean anything really. 

I'm having a difficult time understanding any use case here for middle levels of effort that don't involve substantially complicating the protocols (adding acks) or imposing s storage requirement or ultimately leading to heartbreak due to broken promises.

**Comment by memeplex** [comment] 2015-12-17 12:37
I think that's because you're putting the question in terms of absolute reliability including an ack while I'm just talking about dropping vs blocking behavior which in practice may be enough for more controlled use cases. Here are some relevant posts;

http://www.freelists.org/post/nanomsg/Generalizing-pubsub-distribution,3

http://www.freelists.org/post/nanomsg/Generalizing-pubsub-distribution,6

http://www.freelists.org/post/nanomsg/Generalizing-pubsub-distribution,9

http://www.freelists.org/post/nanomsg/Generalizing-pubsub-distribution,16

http://www.freelists.org/post/nanomsg/Generalizing-pubsub-distribution,18

**Comment by nivan22** [comment] 2015-12-17 12:46
to what I asked for which was a use case.  Tell me what you need to achieve not how you think you want to achieve it.

My instinct here is that tunable levels of delivery "effort" are mostly meaningless. Only req/rep can offer a guarantee and that is because there is an ack that is initiated by the app (rep). No other guarantees actually mean anything really.

I'm having a difficult time understanding any use case here for middle levels of effort that don't involve substantially complicating the protocols (adding acks) or imposing !!

**Comment by memeplex** [comment] 2015-12-17 12:48
All in all it can be summarized to the fact that I think that blocking broadcasting/pub may have similar role than blocking push, and that the 1 vs n dimension is pretty orthogonal to the blocking vs dropping dimension, although I do recognize both the difficulty introduced by partial publication and the different emphasis of the standard use cases for push and for pub. Mainly I find uncomfortable the inability to reuse the great topic routing implementation you have in my own use case.

**Comment by memeplex** [comment] 2015-12-17 12:51
@nivan22 there is long anf detailed description of my use case in the links above, and a short description of another one by Isaac also.

**Comment by gdamore** [comment] 2015-12-17 15:32
Thanks for the links.  It seems I didn't receive nanomsg list email recently so I have to figure that out. 

In the meantime I understand the use case.

I think this approach leads to heartache as people will begin to believe that it can be used for some kind of reliable multicast which is fundamentally impossible without an ack protocol. Usually also a side unicast channel is used. 

Unlike zmq it should be noted that "routing" in nanomsg is implemented as a receiver side filter.  We don't know which channels are interested in a message on the sender side.  So we have to block behind every receiver in the channel.  

Sure there are use cases for this as you've noted.  But those aren't really live and they require extra care on the part of the user. 

The systems that I know that need this for eg training or replay would do so using a saved history file rather than continuing to use an unreliable transport. 

Or they use some kind of unicast synch protocol to catch the subscribers up.  (Note that this requires storage on the server.)

Basically at the point you're doing this you don't want the pub sub semantic at all.  

We could indeed use a form of back pressure on the socket based on all pipes be able to accept a message, but I fear that such an approach is half baked and will only cause more heartache later as people try to use it as some kind of reliable transport which is not what it is. 

I'd be inclined to enable such a mechanism only if a new option were used to enable it - something like NN_WEAKEST_LINK to indicate that the slowest subscriber can halt the entire system. 

Anyway I think a big part of the problem is that you're trying to fit a square peg into a round hole. 

I will think about this.  I'm also open to considering a PR that adds this behavior.

The reality is that right now I have enough other issues to resolve in nanomsg that it's unlikely I'm going to try to address this unless someone else provides a PR.

**Comment by memeplex** [comment] 2015-12-17 18:00
@gdamore thank you very much for your answer, I really meant it. It's difficult for me to assest what people will begin to believe since I've no experience as a library writter in this field. All I could say is that I expect push to block while I'm not expecting it to be fully reliable, thus this doesn't confuse me and I understand that going reliable will imply changing pushpull for reqrep; this level of understanding zmq and nanomsg are already demanding from their users. If I'm pushing too fast I know for sure I will be losing messages and some kind of backpressure is in order, so I rely on the infinite timeout default or set some positive timeout; this level of flexibility zmq and nanomsg are already providing to their users. *Maybe* this could be extended to pub, but as far as the scenario of choice for pub is characterized as "lots of potentially unreliable subs", and not just "n subs", it's clear to me the danger of blocking and that this concern will dominate. Now consider this set of requirements:

1. I want to route using topics.
2. I want to eventually block because my producer is too fast.
3. I know my consumers are just right, I'm not paranoid about them, I've developed them and can fix them in any case.

Surely I can implement that on top of normal pipelines and some kind of simple routing protocol (which will imply some type of announcement, heartbeating, etc.). As I see it I still want *a part* of the pub semantic, and this part is as round or squared as round or squared is my hole number 1 above. Now I do understand your concerns as a library designer and maintainer, and I do understand that the SP idea is not to address vacuous generalizations but concrete albeit general use cases.

Would your suggestion of `NN_WEAKEST_LINK` be for any interested SP to comply or just for pub? For example, what about rep?

Don't hold your breath for a PR (I don't expect you will in this case, anyway :) ), but eventually I will realize I'm wrong or tackle this.

**Comment by nivan22** [comment] 2015-12-17 18:03
to be fully reliable, thus this doesn't confuse me and I understand that going reliable will imply changing pushpull for reqrep; this level of understanding zmq and nanomsg are already demanding from their users. If I'm pushing too fast I know for sure I will be losing messages and some kind of backpressure is in order, so I rely on the infinite timeout default or set some positive timeout; this level of flexibility zmq and nanomsg are already providing to their users. Maybe this could be extended to pub, but as far as the scenario of choice for pub is characterized as "lots of potentially unreliable subs", and not just "n subs", it's clear to me the danger of blocking and that this concern will dominate. Now consider this set of requirements:

I want to route using topics.
I want to eventually block because my producer is too fast.
I know my consumers are just right, I'm not paranoid about them, I've developed them and can fix them in any case.
Surely I can implement that on top of normal pipelines and some kind of simple routing protocol (which will imply some type of announcement, heartbeating, etc.). As I see it I still want a part of the pub semantic, and this part is as round or squared as round or squared is my hole number 1 above. Now I do understand your concerns as a library designer and maintainer, and I do understand that the SP

**Comment by gdamore** [comment] 2015-12-17 18:22
So NN_WEAKEST_LINK would be for any multicast type distribution.  For protocols that are strictly 1:1 (PAIR, and PUSH/PULL) I think the existing timeout options already work, and this shouldn't be needed.

The multicast protocols are PUB/SUB, BUS, and (mangos only) STAR.

This absolutely would *NOT* apply to REQ/REP.  We already have both timeouts and reliable (ack'd) delivery for those protocols.

**Comment by memeplex** [comment] 2015-12-17 18:23
Isn't rep always dropping?

**Comment by gdamore** [comment] 2015-12-17 18:23
Well, actually, only REQ is ACK'd, but the synchronous nature of REP means that REP should never be flow controlled behind a REQ.

Unless one is using raw sockets.  Then all bets off, because you have multiple outstanding REQs.  I have no idea how you deal with that.

**Comment by gdamore** [comment] 2015-12-17 18:25
But even if the REP is dropped, the lost ACK should cause the REQ to try again.  You'd best be sure that your requests are idempotent though.

**Comment by memeplex** [comment] 2015-12-17 18:26
Good point.
