### ISSUE TITLE
Suggestion: pre-compiled binaries

### ISSUE THREAD

**Issue by kroggen** [nanomsg/nanomsg#808] opened 2016-09-21 18:41 UTC
Hi guys!

Now that we have a production release, why not have a pre-build binaries?

At least for Windows. What about an installer?

It can be a single installer for x86 as it may work on x64 too.

**Comment by gdamore** [comment] 2016-09-21 21:20
Would like to, but have to think through what exactly this means for a
shared library on Windows.

 - Garrett

**Comment by kroggen** [comment] 2016-09-22 00:45
Here is one idea:

One installer with 2 options:

Option 1: For end-user

It installs just the nanomsg.dll in the Windows system folder. Nothing more.

Option 2: For developers

It installs all the files in a selected folder, including:

nanomsg.dll
nanomsg.lib
nn.h and other include files

One question we need to answer is if the shared library will depend on MSVCRT or not. Compiling with Visual Studio will make it depend on MSVCR100.DLL (or another version). I guess we cannot make it depend on MSVCRT.DLL, which is already shipped with all Windows. Maybe compiling with GCC.

Or then make it stand-alone. It will be a bit bigger in size but no dependencies on a C run-time library.

The key is to make it useful for ourselves to have the library when we are using computers that do not have Visual Studio installed.

**Comment by gdamore** [comment] 2016-09-22 01:37
the question i have is what value an end user install has.  if i was developing an app i would just bundle the library with my app.

**Comment by kroggen** [comment] 2016-09-22 02:34
I was with the same doubt. Maybe it is not needed. Just an installer for developers would be sufficient.

**Comment by kroggen** [comment] 2016-09-22 02:36
Well, if we don't need to put the DLL into the system folder, then we don't even need an installer. Just the files in a zip folder would do the job.

**Comment by kroggen** [comment] 2016-09-22 02:49
And the build can be automated via AppVeyor to minimize future work on new releases.

But I don't know exactly how to configure the [`.appveyor.yml`](https://github.com/nanomsg/nanomsg/blob/master/.appveyor.yml) file to copy the compiled files to the GitHub releases. And it should be added a Release build as now there are only Debug builds there.

**Comment by kroggen** [comment] 2016-10-08 20:48
Hi!

I am trying to implement it via AppVeyor but I can't make it to work.

The builds are here: https://ci.appveyor.com/project/kroggen/nanomsg

My forked config file is [here](https://github.com/kroggen/nanomsg/blob/master/.appveyor.yml)

I don't know how to produce binaries for both 32 and 64 bits using the cmake.

And I cannot make AppVeyor create the artifact that it needs to upload to GitHub releases.

I am reading the [appveyor.yml reference](https://www.appveyor.com/docs/appveyor-yml/)

Any ideas?

**Comment by Snaipe** [comment] 2016-10-08 20:59
@kroggen you need to source `vsvars64.bat` when building x64 executables. I would suggest you duplicate the nmake matrix entry to do just that (or add `platforms: [32, 64]` and substitute `%PLATFORM%` when sourcing the vsvars).

As for deploying, perhaps take a look at my own config: first, [create a tarball with the installed contents](https://github.com/Snaipe/Criterion/blob/bleeding/appveyor.yml#L73-L79) and then [deploy it on github](https://github.com/Snaipe/Criterion/blob/bleeding/appveyor.yml#L92-L101). You'll need a deploy token for the second part though, so you won't really be able to do that yourself.

**Comment by kroggen** [comment] 2016-10-08 22:41
Thank you @Snaipe !  I will try.

**Comment by kroggen** [comment] 2016-10-09 04:47
Sorry guys, I give up!

I cannot create a simple zip file and set as an artifact! It keeps showing errors with the variables.

I hope you can continue this.

Check the changes I've made in the [appveyor.yml](https://github.com/kroggen/nanomsg/blob/master/.appveyor.yml) file

I tried :

cmd: set archive = nanomsg-$(RELEASE_NAME)-windows-$(PLATFORM).zip
cmd: echo "%archive%"
cmd: 7z a "%archive%" nanomsg.dll nanomsg.lib src\*.h

And it does not work. I tried %archive% (without the quotes), "$(archive)", $(archive)... and no one worked...

I also tried with PowerShell and got only errors...

I cannot handle these variables.

**Comment by Snaipe** [comment] 2016-10-09 10:44
The errors you are getting are there because you cannot assume the place where nanomsg.dll is built with cmake (it depends on the generator). Install the project to a known directory beforehand and zip that directory.

**Comment by gdamore** [comment] 2016-10-09 16:06
cpack would be the preferred way to so this.  I still have my basic questions about whether this is useful or not.

**Comment by gdamore** [comment] 2016-10-20 03:33
This is a duplicate of #729

**Closed by gdamore** 2016-10-20 03:33 UTC
