### ISSUE TITLE
Linux: trying to use an ipc protocol with a file which can't be created doesn't fail.

### ISSUE THREAD

**Issue by krafczyk** [nanomsg/nanomsg#401] opened 2015-04-14 20:18 UTC
If I try to create an ipc protocol socket with a file path which can't be created for some reason (need to make a directory, no permission etc...), The nn_bind and nn_connect functions do not return an integer < 0.

For example, if I do:

int socket = nn_socket(AF_SP, NN_PAIR);
int endpoint = nn_bind(socket, "ipc:///temp/username/temp.ipc");

or

int socket = nn_socket(AF_SP, NN_PAIR);
int endpoint = nn_connect(socket, "ipc:///temp/username/temp.ipc");

if the directory /temp doesn't exist, then the endpoint will not be < 0.

Interestingly, if I set errno=0 just before the call to nn_bind or nn_connect, then I check, it get's set to 2 (No such file or directory) Which is correct.

Also, if I turn on terminal debugging with NN_PRINT_ERRORS, The program which calls nn_bind doesn't print any errors, but if I try to connect to that ipc file with nn_connect, the program gets the message:

nanomsg: socket.0[/temp/username/temp.ipc]: Error: No such file or directory

But the return value of nn_connect is still >= 0.

**Comment by gdamore** [comment] 2015-05-02 21:34
This behavior is as designed; the nn_bind and nn_connect calls will attempt to rebind/reconnect at periodic intervals.  This is to help them act in a "self-healing" capacity.

There is a proposal to add per-endpoint errno reporting, which may improve visibility into these problems somewhat, but modulo that, these functions are not intended to fail, ever.  Even if they don't establish a connection.

This behavior may seem surprising at first, but its that self-healing component that justifies it.  You just use them and don't worry if there is a temporary problem.  (Arguably some errors will *always* be fatal, and it would be nice if we could identify those and return such a hard failure, but figuring out which errors cannot ever be corrected is non-trivial.)

Meantime, I'm closing this as "not a bug".  (Or rather, intentional design feature.)

**Closed by gdamore** 2015-05-02 21:34 UTC
