### ISSUE TITLE
Closing sending side of inproc connection blocks receiving side permanently

### ISSUE THREAD

**Issue by jonhoo** [nanomsg/nanomsg#244] opened 2014-05-19 15:58 UTC
If two threads each have sockets connected to the same endpoint using the inproc transport and one thread calls `nn_close` on its socket, the other thread will block indefinitely upon calling `nn_recv` even if there are messages in the queue.

I've observed this with both the pipeline protocol and the pair protocol.
Minimal test case: http://pastebin.com/56n1dtRh
The problem does not seem to consistenly manifest when only using two threads.

**Comment by gdamore** [comment] 2015-06-01 04:16
I believe that this may be another case of #411 -- but also inproc seems to have problems with thread safety.  IPC should be better.

**Comment by gdamore** [comment] 2015-10-24 23:53
Closing this as a dup of #429

**Closed by gdamore** 2015-10-24 23:53 UTC

**Comment by gdamore** [comment] 2017-10-13 00:03
Actually reading the code, this is not actually a bug.  Your code somehow manages to assume that recv() is going to work -- but if there is no party on the other side, then nn_recv() blocks indefinitely.  This is the nature of nanomsg -- sockets are not a 1:1 connection, but can have multiple parties.

Your sample code also had other problems (like wait being a well known symbol, and missing an include for stdbool.h

Nonetheless I fixed the minor compilation issues, and tested, and traced, and determined that the problem is in your expectations, not in inproc or nanomsg.
