### ISSUE TITLE
error: unknown type name

### ISSUE THREAD

**Issue by kd7tck** [nanomsg/nanomsg#738] opened 2016-05-27 23:58 UTC
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Joshua>cd C:\Users\Joshua\Desktop\build

C:\Users\Joshua\Desktop\build>mingw32-make
Scanning dependencies of target nanomsg
[  1%] Building C object src/CMakeFiles/nanomsg.dir/core/ep.c.obj
[  1%] Building C object src/CMakeFiles/nanomsg.dir/core/epbase.c.obj
[  2%] Building C object src/CMakeFiles/nanomsg.dir/core/global.c.obj
In file included from C:\Users\Joshua\Desktop\nanomsg-0.9-beta\src\core\global.c:39:0:
C:\Users\Joshua\Desktop\nanomsg-0.9-beta\src\core\../utils/condvar.h:31:5: error: unknown type name 'CONDITION_VARIABLE'
     CONDITION_VARIABLE cv;
     ^
In file included from C:\Users\Joshua\Desktop\nanomsg-0.9-beta\src\core\global.c:40:0:
C:\Users\Joshua\Desktop\nanomsg-0.9-beta\src\core\../utils/once.h:29:5: error: unknown type name 'INIT_ONCE'
     INIT_ONCE once;
     ^
In file included from C:\Users\Joshua\Desktop\nanomsg-0.9-beta\src\core\global.c:40:0:
C:\Users\Joshua\Desktop\nanomsg-0.9-beta\src\core\../utils/once.h:31:31: error: 'INIT_ONCE_STATIC_INIT' undeclared here (not in a function)
 #define NN_ONCE_INITIALIZER { INIT_ONCE_STATIC_INIT }
                               ^
C:\Users\Joshua\Desktop\nanomsg-0.9-beta\src\core\global.c:145:25: note: in expansion of macro 'NN_ONCE_INITIALIZER'
 static nn_once_t once = NN_ONCE_INITIALIZER;
                         ^
src\CMakeFiles\nanomsg.dir\build.make:109: recipe for target 'src/CMakeFiles/nanomsg.dir/core/global.c.obj' failed
mingw32-make[2]: *** [src/CMakeFiles/nanomsg.dir/core/global.c.obj] Error 1
CMakeFiles\Makefile2:1892: recipe for target 'src/CMakeFiles/nanomsg.dir/all' failed
mingw32-make[1]: *** [src/CMakeFiles/nanomsg.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by gdamore** [comment] 2016-05-28 00:59
MinGW is not a supported environment.  You *can* build with MinGW-w64.  (The problem is various newer APIs are not supported by MinGW, including, as you've noticed, condition variables.)

I'm closing this as *will-not-fix*, not a bug, etc.

**Closed by gdamore** 2016-05-28 00:59 UTC
