### ISSUE TITLE
Can't send big file

### ISSUE THREAD

**Issue by songmaotian** [nanomsg/nanomsg#961] opened 2018-04-07 15:03 UTC
I am trying to send a file in 18MB
./nanocat --pub --bind tcp://*:1200 -F bigfile --interval 1

but can't receive the file
./nanocat --sub --connect tcp://127.0.0.1:1200 --ascii

Is there a length limit for the protocol?

**Comment by gdamore** [comment] 2018-04-07 15:07
not for the protocol but there is a default limit of 1 MB to protect
against DoS. unfortunately nanocat doesn’t have a command line option to
access the setting to change that (NN_RECVMAXSZ).

**Comment by songmaotian** [comment] 2018-04-07 22:32
@gdamore sorry, but how to change the size? I grep, but can't find the macro.

**Comment by songmaotian** [comment] 2018-04-07 23:12
@gdamore I write a code
if (nn_setsockopt(sock, NN_SOL_SOCKET, NN_RCVMAXSIZE, &size, sizeof(size)) < 0) {
to set NN_RCVMAXSIZE, but the program received a segment fault.

**Comment by gdamore** [comment] 2018-04-14 18:00
I'd also like a backtrace from the segfault, so I can see where it failed.

**Comment by gdamore** [comment] 2018-04-23 16:33
Submitter, ping?

**Comment by gdamore** [comment] 2018-05-01 21:46
So, if you're sending or receiving large data, you have to be aware that nn_send can unfortunately block.  This is an unfortunate consequence of the fact that nanomsg does not provide any buffering, so there is no separate thread to do the send, instead it just steals the context from the calling thread.

For small messages this isn't a problem, since we can usually send or receive a full TCP segment at a time (or a some amount of chunked data for an IPC pipe).  The problem is that when your data size is larger than a TCP segment, we can see poll() tell us it's ready for data, but so we start an operation, but it can't complete all the way.

If the operation was done with a non-blocking operation, then this will ultimately return a partial completion followed by EAGAIN.  If it was blocking, your application will "hang" until the operation completes.  If the other side is slow to receive and ack the data, this can lead to a complete stall.

The nng project (github.com/nanomsg/nng) offers an API that is compatible with libnanomsg, but has a very different internal architecture, that should be immune from this problem.  I recommend you give that a try.

**Comment by gdamore** [comment] 2018-05-23 02:53
I'm going to close this for now... no feedback from the original submitter.

Ultimately, I recommend giving NNG a shot.

**Closed by gdamore** 2018-05-23 02:53 UTC
Labels: awaiting feedback

**Comment by weihu8687** [comment] 2018-06-04 09:37
I see the same problem as I want to send/recv a 6MB file. after call 
if (nn_setsockopt(sock, NN_SOL_SOCKET, NN_RCVMAXSIZE, &size, sizeof(size)) < 0) {}
it works, and I don't see the segment fault.

**Comment by xoyojank** [comment] 2018-06-04 12:10
what's the size you set?

**Comment by weihu8687** [comment] 2018-06-05 01:42
I set to 6*1024*1024, doesn't try bigger setting.

**Comment by gdamore** [comment] 2018-06-05 01:59
I'm also wondering, but haven't looked, if nanocat has any internal limitations on the message sizes.  The nngcat that ships with NNG program does not, and I've tested it with larger buffers -- say 10MB, without problems.
