### ISSUE TITLE
atcp.c abort on Windows Platform

### ISSUE THREAD

**Issue by xwbeast** [nanomsg/nanomsg#993] opened 2018-09-28 07:15 UTC
My application is running on Windows Platform and Linux Platform at the same time with Pair Mode, the windows platform is running with bind and linux with connect. After few hours, the application running on Windows abort with this error : (Unexpected action: state=2 source=1 action=5 (e:\workspace\nanomsg-1.1.4\src\transports\tcp\atcp.c:228).

**Comment by gdamore** [comment] 2018-11-22 04:47
I believe this problem is arising due to a potential "race" relating to the close of the created socket.  The code here is fragile, and has many assertions where the original author didn't think through all the cases.  (The same is true of ZeroMQ as well.) . If you have a chance, I'd recommend giving NNG a shot (github.com/nanomsg/nng) which was designed to be robust from the first day.

Having said that, if I find time to work on this I'll fix it.  But right now nanomsg is definitely backburnered compared to NNG.  (If you need support commercially, reach out to me separately -- we can work out a solution that should let you get a fix for this faster.)

**Comment by gdamore** [comment] 2024-02-18 00:31
This is ancient.  I'm going to close this due to age.  This may not be very satisfactory, but there have been fixes made; if you can try a newer version and it still happens, please go ahead and reopen this or submit a new ticket.

**Closed by gdamore** 2024-02-18 00:31 UTC
