### ISSUE TITLE
Unable to do pubsub binding a subscriber

### ISSUE THREAD

**Issue by ksvasan** [nanomsg/nanomsg#351] opened 2014-12-21 20:34 UTC
When I try to communicate with pubsub sockets over IPC. I'm able to publish and subscribe to topics while debugging but I'm unable to receive messages while running them in non-debug mode. Is there something to do with the library implementation? For both of them I use url=ipc:///tmp/bob.ipc and topic=hello and always start the subscriber (bind) first and then publisher (connect). I've tried waiting for sometime with subscriber and then starting the publisher to no avail. Kindly help me with the info, if can we bind the subscriber at all in nanomsg (so we need not worry about missing messages)

Publisher:

    #include <stdio.h>
    #include <string.h>
    #include "nanomsg/nn.h"
    #include "nanomsg/pubsub.h"

    #define MAXSIZE 1024

    int main(int argc, char *argv[]) {
        int pub = nn_socket(AF_SP, NN_PUB);
        int rc = 0;
        if (argc <= 1) {
            printf("Usage: %s <url>\n", argv[0]);
            return 1;
        }   

        char *url = argv[1];
        char buf[MAXSIZE] = "hello, world";
        rc = nn_connect(pub, url);
        if (rc < 0)
            perror("Unable to connect to URL");
        nn_send(pub, buf, strlen(buf), 0); 
        nn_shutdown(pub, 0); 
        return 0;
    } 

Subscriber:

    #include <stdio.h>
    #include <string.h>
    #include "nanomsg/nn.h"
    #include "nanomsg/pubsub.h"

    int main(int argc, char *argv[]) {
        int sub = nn_socket(AF_SP, NN_SUB);
        int rc = 0;
        if (argc <= 2) {
            printf("Usage: %s <url> <subject>\n", argv[0]);
            return 1;
        }   

        char *url = argv[1];
        char *topic = argv[2];
        char *buf = NULL;
        rc = nn_bind(sub, url);
        if (rc < 0) {
            perror("Unable to bind socket");
            return 2;
        }   
        rc = nn_setsockopt(sub, NN_SUB, NN_SUB_SUBSCRIBE, topic, strlen(topic));
        if (rc) {
            perror("Unable to set socket option");
            return 3;
        }   
        rc = nn_recv(sub, &buf, NN_MSG, 0); 
        if (rc < 0) {
            perror("Unable to receive data");
            return 4;
        }   
        printf("Received msg: %s\n", buf);
        nn_freemsg(buf);
        nn_shutdown(sub, 0); 
        return 0;
    }

**Comment by gdamore** [comment] 2015-06-01 04:29
You're sending the message too soon, and not waiting long enough before shutting down the socket. 
Recall that nanomsg is asynchronous, and when you exit too quickly, or if you send the message without giving time for the connection to establish yet, the message may not be delivered.

By adding a sleep(1) before and after the nn_send(), your program works.

See lots of information about TCP slow start, and SO_LINGER.  While you're not using TCP, the same problems are applicable.

REQ/REP (acknowledged messages) are generally free of this problem.

Closing this as its a simple API usage problem, and not a bug in nanomsg.

**Closed by gdamore** 2015-06-01 04:29 UTC
