### ISSUE TITLE
a problem for "nn_close" call

### ISSUE THREAD

**Issue by panjw** [nanomsg/nanomsg#473] opened 2015-10-14 07:57 UTC
first: my code call ''nn_bind" function ,but tcp port is invalid for listen ;now btcp->atcp is null;
        btcp->atcps is null; btcp->usock is idle;btcp->retry timer is start
second:  a problem cause by call "nn_close" function,code stack as follow:

This is function call stack 
raise () from /lib64/libc.so.6
 abort () from /lib64/libc.so.6
nn_err_abort () at src/utils/err.c:33
nn_timer_term (self=self@entry=0x99dba0) at src/aio/timer.c:62
nn_backoff_term (self=self@entry=0x99dba0) at src/transports/utils/backoff.c:36
nn_btcp_destroy (self=<optimized out>) at src/transports/tcp/btcp.c:205
nn_ep_term (self=self@entry=0x99d7a0) at src/core/ep.c:88
nn_sock_shutdown (self=0x993c50, src=<optimized out>, type=<optimized out>, srcptr=0x99d7a0) at src/core/sock.c:831
nn_ctx_leave (self=self@entry=0x993cc8) at src/aio/ctx.c:63
nn_sock_term (self=0x993c50) at src/core/sock.c:198
nn_close (s=10) at src/core/global.c:562

**Comment by gdamore** [comment] 2015-10-21 19:35
I think this commit 5cd676c50961c1bf30f7babefc0c3d7978ec5112 may have solved your problem.  Can you update and try again?

**Comment by gdamore** [comment] 2015-10-21 19:35
To be clear, this looks like another issue for #463 -- possibly.

**Comment by gdamore** [comment] 2015-11-09 18:49
Ping?  @panjw can you check nanomsg 0.7?

**Comment by gdamore** [comment] 2015-11-13 01:55
Is this #65 -- I think so.  If it is a hang on nn_recv after nn_close(), I have a fix coming.

**Comment by gdamore** [comment] 2015-11-16 01:05
nn_close() is confirmed to have some ugly races in it.  Stay tuned for the fix, I hope.

**Comment by panjw** [comment] 2015-11-16 02:02
thans ,the problem have be fix

**Comment by gdamore** [comment] 2015-11-16 02:29
Closing per feedback from submitter.

**Closed by gdamore** 2015-11-16 02:29 UTC
