### ISSUE TITLE
Sending packets from command line go utility

### ISSUE THREAD

**Issue by BillMcCroskey** [nanomsg/nanomsg#689] opened 2016-05-04 20:03 UTC
We have several utilities for sending packets for software unit test on the various buses (pipeline, pub/sub, bus).  All connections are ipc on Unix Domain Sockets. The utilities open the socket, send the packet and data specified on the command line, and then close the socket.  This is much like the nanocat program, but with custom packets.
The problem is, not all of the packet may get through the "door" before the socket is closed. As a note, nanocat only sends correctly when using the -i option and it keeps the socket open.  What I was wondering was if anything in Go could work like the nn_poll option in 'C'.  The idea would be to send and then check for when another packet could be sent without blocking, and then close the socket.  The goal is to try to know when the packet made it to the Unix Domain Socket layer and hopefully to the receivers before closing.  The net effect of this problem is clients on a sub bus do not get the packets.  Using strace, I was able to see clients receiving partial packets, and some packets were so short they never got through the domain socket handling.  So a short packet will either get dropped by the domain sockets, the subscriptions, or the processing of flatbuffer data in the packet.
Trying to find a solution to get the full packet on the "wire".

**Comment by gdamore** [comment] 2016-05-04 22:13
I'm not sure how big your messages are.  UNIX domain sockets may limit your data sent to 576 bytes at a time.

There is a linger socket option, but I don't think it is used for UNIX domain sockets, only for TCP.  And I'm not sure that even that covers it completely.

If you're using Go, I recommend using mangos.  Mangos does have have a linger option (OptionLinger) which may help you.   The linger is given in a time.Duration, and mangos will attempt to wait until its queues are empty, or that timeout has expired.  Its still not perfect, because you can lose data -- indeed close() of a UNIX file descriptor can result in the data being dropped in the kernel even after write() completes and there's not much we can do about that.

If you're truly paranoid, you need to have an ACK message back.  That is, you cannot know for sure that the other side received the data *unless* it *tells* you so (and you *hear* -- or receive -- such a message).

If you're just testing, you could have an ACK on a secondary channel (req/rep, or even a PUB/SUB in reverse) to let the sender know the message was received.

**Comment by gdamore** [comment] 2016-05-04 22:14
Oh, also naively, you could just inject  a sleep before exiting.  Its not ideal, but simple, and as long as your messages are not too big and you have connectivity, it should work.

**Comment by BillMcCroskey** [comment] 2016-05-06 11:52
Yes, using Mangos for Go.  Most packets are much under the 576.  Might try the time delay as a quick fix.  Longer solution might be to fire up a process on the first one that sits on the socket and then the command-line facing half posts IPC to the service and then command a shutdown as needed at end.
Thanks!

**Comment by gdamore** [comment] 2016-05-09 16:14
Closing- not a bug.

**Closed by gdamore** 2016-05-09 16:14 UTC
