### ISSUE TITLE
Assertion failed: type == NN_USOCK_ERROR

### ISSUE THREAD

**Issue by deepakprabhakara** [nanomsg/nanomsg#870] opened 2017-04-05 08:46 UTC
I see the following log line occasionally on our backend - "Assertion failed: type == NN_USOCK_ERROR (../deps/nanomsg/src/transports/utils/streamhdr.c:264)". Things still continue to work though.

Could someone please shed light on why this could be happening so I can track down what I am doing wrong and fix it.

Regards.
Deepak.

**Comment by gdamore** [comment] 2017-05-12 20:33
I need more information here; most likely you have a TCP connection that has been aborted during the connection establishment phase, and the state machine is somewhat unhappy about that.  Having said that, I thought we had addressed most of these.  Can you tell me what version you tested with?

**Comment by deepakprabhakara** [comment] 2017-05-13 11:44
Thanks @gdamore. I am using nanomsg 1.0, however I am not seeing this anymore so not sure if I can get a predictable test to reproduce it. Will post back if I progress further on this.

**Comment by gdamore** [comment] 2017-10-11 19:27
I'm pretty sure this is a dup of #895 (or rather 895 is a dupe of this, but for now I'm using 895 to track it.)  A fix is about to be pushed.

**Closed by gdamore** 2017-10-11 19:27 UTC

**Comment by deepakprabhakara** [comment] 2017-10-12 09:23
Excellent, thank you.
