### ISSUE TITLE
Need `test_shutdown()` wrapper in testing utilities

### ISSUE THREAD

**Issue by JackDunaway** [nanomsg/nanomsg#580] opened 2015-12-15 03:03 UTC
Much of the Public API is harnessed within convenient functions for testing https://github.com/nanomsg/nanomsg/blob/master/tests/testutil.h, except we need one for `nn_shutdown()`

**Comment by gdamore** [comment] 2015-12-17 00:52
I'm actually pulling this out of the PR, because it appears that nothing uses it.  Just adding API for 'internal' use without internal consumption is not good -- you need to add at least one consumer at the same time.  This ensures that an example of correct use exists, and helps guard against pointless bloat caused by "useful" functions that aren't actually used.

**Comment by wirebirdlabs** [comment] 2015-12-17 03:16
It's OK to pull it out of #578 (agree with all your reasons), but it's used in #569. Let's table this one for now.

**Comment by gdamore** [comment] 2017-01-21 01:22
We're off the track with this, and I've moved onto libnng.  Let's close this for now, and focus on libnng.

**Closed by gdamore** 2017-01-21 01:22 UTC
