### ISSUE TITLE
pubsub drop packet in ipc mode when i have 2 or more subscribers under linux

### ISSUE THREAD

**Issue by ddway2** [nanomsg/nanomsg#321] opened 2014-10-23 12:48 UTC
Hi
My behavior is the following:
 - when i used 1 subscribing, pubsub in IPC flood work fine
 - when i used 2 or more subscribing, pubsub in IPC flood drop packet

If i switch in TCP mode, i have no problem but it isnt good solution

I'm under Linux Debian jessie with gcc 4.9

**Comment by gdamore** [comment] 2015-06-01 03:57
I've changed the sub/pub protocol recently.  Can you please try again?

Note also that PUB/SUB is best effort delivery.  If the underlying transport cannot deliver a message due to TCP backpressure, the messages are blithely discarded.  This implies that your SUB has to run at least as fast as your PUB.  And as you may know, filtering is done on the receiver side, so the SUB has to be able to process (at least for filtering) messages at least as fast as the PUB runs.

Note that the IPC channels are somewhat limited, and will apply backpressure even faster than TCP in some cases.

**Comment by gdamore** [comment] 2015-10-24 16:36
If you're flooding IPC, you have to expect message drops.  This is expected behavior.  Closing.

**Closed by gdamore** 2015-10-24 16:36 UTC
