### ISSUE TITLE
Multi-Client Single-Server Design question

### ISSUE THREAD

**Issue by filcuc** [nanomsg/nanomsg#809] opened 2016-10-03 17:45 UTC
Hi i played a little with nanomsg and i highly appreciated its design with built in protocols and the message abstraction.
Given that i tried to model a common scenario where i've 1 or more clients and a single server. After a login phase each client should communicate separately with the server (two way).
I modeled this with 
1) A REQ-REP socket (respectively client[REQ] server[REP] 
2) Multiple PAIR 
During (1) each client sends a message that contains the endpoint of its PAIR socket (so the socket is bond on the client and the server connect). The server simply spawn a new thread that connect a PAIR socket to the client endpoint.
This somewhat works but has the downside of making the client publicly reachable (and this is not the case with "normal" socket programming since the socket is already a two way channel and the communication start from the client to the server).

Another option could be to slightly modify the previous method by making the server bind the PAIR socket and send its endpoint address to the client during (1). This nicely solves the problem of having the client address reachable but again there's a downside: we are limited to 65000 client since we have to use a different endpoint for each one.

Am i missing something? Should i move to a different solution or technology? am i using nanomsg incorrectly?

**Comment by Crest** [comment] 2016-10-04 09:04
Yes you're missing something. The nanomsg design implements a set of common communication patterns. A general rule of thumb is that applications shouldn't create new nanomsg sockets after they're initialised. Of course the nanomsg library creates multiple TCP or unix domain sockets at runtime to implement the abstraction offered by the nanomsg sockets.

Using multiple nanomsg sockets can simplify you application logic, but it forces you to use multiple ports/paths for your bound sockets or use the experimental WebSocket transport which multiplexes multiple nanomsg sockets through a single TCP port.

If all communication is initiated by the client a single REP socket in the server is enough. You can either authenticate every request or perform a (multistage) handshake e.g. provide the client with a HMAC protected token. I would separate the session management into its own service.

If you need a backchannel from your server to the client things get messier. A common solution is a PUB socket in the server but iirc nanomsg doesn't filter subscriptions in the server. And workarounds like long-poll requests don't work with the stateful REQ-REP socket abstraction. This a limitation of the nanomsg implementation. The REQ-REP scalability protocol could handle this long poll requests, but would require application support in the form of timeouts and retires creating some traffic to keep all the buggy middleboxes encountered on the internet happy.

**Comment by gdamore** [comment] 2016-10-06 03:49
It sounds to me like what you want is a star-like topology, with logic in the center.

You need to define your own application layer protocol for this, so that your central server can figure out where to route messages to.

Then you could use a bunch of PAIR sockets (assuming you are willing to tolerate message drops due to backpressure).  Each client would have a single socket on the server.  Imagine a protocol like this:

You have these primitives sent by clients to the server:

LOGIN
  - sends a unique client ID
  - as well as any other useful identifying information
LOGOUT
  - indicates clean disconnect
SEND
  - posts the unique client ID of the destination
  - includes the message payload
  - server can determine sender by the socket on which the message arrives

Then the server can send messages to clients like this:

  - OK  - indicates a message was queued for delivery (maybe delivered, maybe not) or other good result
 - FAIL - e.g. if the destination of the last message send request couldn't be done because no such client, etc.
 - RECV
      - server changes SEND to this, and swaps the destination client ID for the originators ID

The above values could just be leading bytes in the data stream/messages. 

Multithreaded, I'd have one thread sending, and another receiving.  They could probably run completely asynchronously to each other.

In this case nanomsg isn't doing a lot for you, except automatically handling the framing. 

The critical thing here is that you need application logic to determine *where* to forward a message to.  That's the logic in the server, that has to inspect destinations for SEND frames, and rewrite those (and forward them to the appropriate socket.)  The server will need to use the multithreaded support and the cmsg API to do this properly.

**Comment by gdamore** [comment] 2016-10-06 03:50
Closing this as its a question, not a bug.

**Closed by gdamore** 2016-10-06 03:50 UTC

**Comment by zwxf** [comment] 2019-03-07 09:46
@gdamore Hi:
    From you comment, i found Pair is peer 2 peer, if i want a peer connect to multi peer does means need multi thread? any another ways to achieve star-like topology?
    Best regard!

**Comment by gdamore** [comment] 2019-03-07 15:50
BUS can be used to create a star topology.  Its the central node will broadcast to all peers, whereas the leafs will only send to the hub.

If you use NNG instead, you'll have access to PAIRv1 Polyamorous mode, which is a bit more capable for establishing multiple 1:1 relationships.

Golang users have STAR as an option as well, from within mangos.  I've long had plans to introduce STAR into NNG, just haven't gotten to it yet.

**Comment by zwxf** [comment] 2019-03-08 01:24
OOK，It seems works, but leafs should bind a address and hub should connect to all leafs, so if i want add more leafs should compile the hub again(can not sepatate two part individually),may be NNG is a good choice, otherwise my code is running in the embeded system(IXM6UL linux platform), So NNG may be a good chioce, Last question, is NNG Stable enough for now?
    thanks! hopefor you reply.

**Comment by gdamore** [comment] 2019-03-08 06:17
NNG is indeed stable.  I encourage anyone thinking of using nanomsg to use NNG instead.

**Comment by nivihelen99** [comment] 2020-05-17 21:00
I am learning nng and I have a similar design request. I have one central server which talks to multiple clients and both server and client can talk freely. I tried to do this in zeromq  with server in Router mode and clients in dealer mode and using socketid to identify the clients. 
To do to this NNG, I understand from the above discussion, we need a bunch of pair sockets and perhaps use BUS for server to do one way broadcast and clients use the pair to talk freely to server.
If my understanding correct. I havent used the  PAIRv1 Polyamorous mode yet.  I am very new to NNG.  
Please advise if my approach is correct.

Thanks
