### ISSUE TITLE
Using nanomsg with Java, C#, Delphi and FreePascal together

### ISSUE THREAD

**Issue by mdbs99** [nanomsg/nanomsg#919] opened 2017-10-18 16:29 UTC
I would like to use nanomsg with some different languages and I have some questions, if you allow me:

1. I didn't find a bind to Pascal (Delphi and FreePascal). Is there an official one?
1. I didn't find any pre-compiled library, specifically for Windows. Is this exists anywhere?
1. The README says that "Windows Vista or newer (Windows XP and 2003 are NOT supported)". Is it not supported to *run** or just to compile? In my case, I just want to use the pre-compiled library.
1. I would like to use IPC. On Windows, is this will work using WM_COPYDATA messages? Is there some restriction? Can I could use in FastCGI applications which may have communicate with others Exe using this library?

Thanks.
Best regards.

**Comment by gdamore** [comment] 2017-10-18 18:56
I'm not aware of a Pascal or Delphi binding.  It probably would not be hard to make one.

We don't deliver precompiled binaries.  Maybe someone has built them, but the problem is that I'm actually sure what the best way to deliver precompiled libraries for Windows is, given that there are static and dynamic variants, and 32 and 64-bit versions.  (Never mind also ARM and x86.)  We actually recommend using static compiles for WIndows (and frankly if I had my druthers a static library would be the default output.)  Having said that, I'm open to making a binary distribution if someone can point me in the right direction.

We do use API calls that are not available on Windows XP and 2003 -- so these are non-starters even at run time.  Sorry.  Those systems are long since unsupported.

IPC on Windows works using named pipes.  (Note that mangos -- the go version -- does not support this yet, but its on the TODO.)  I'm not familiar with WM_COPYDATA -- I believe we just use normal byte oriented ReadEx and WriteEx on Windows, using Windows named pipes.

Applications using the IPC layer on Windows can communicate with other applications using the same IPC URL (e.g. ipc:///someplace) on the same Windows machine.  (We do not support IPC over the network, even though I believe some named pipes can be configured this way on Windows.  If you want to go over the network use TCP.)

**Comment by mdbs99** [comment] 2017-10-18 19:24
> I'm not aware of a Pascal or Delphi binding. It probably would not be hard to make one.

There are tools that convert the most C header to Pascal.

> We do use API calls that are not available on Windows XP and 2003

Unfortunately, my clients (some of them) are still using this Windows version to run some systems that I built.

> IPC on Windows works using named pipes. (Note that mangos -- the go version -- does not support this yet, but its on the TODO.) I'm not familiar with WM_COPYDATA -- I believe we just use normal byte oriented ReadEx and WriteEx on Windows, using Windows named pipes.

I've already seen some implementation that using this approach on Windows and pipes on Linux.

About IPC I just want to use on the same machine.

Nanomsg looks like simpler than ZeroMQ, for example, and I would like to use it. But I need to consider its features and restrictions.
I will research more about my options.

If you want, you can close this issue. Thank you.

**Comment by gdamore** [comment] 2017-10-24 22:58
So I started to look at Delphi... but those guys are *nuts* -- they want you to buy Professional license to unlock anything more than 32-bit windows support, or when you reach $1k revenue.  The cost of the professional license is about $1600 -- so literally they intend to *kill* any one starting a business developing products in Delphi.

There's Free Pascal. not sure how portability across versions is.

**Comment by gdamore** [comment] 2017-10-24 22:59
Closing this for now.  Maybe someone will make a Pascal binding.

**Closed by gdamore** 2017-10-24 22:59 UTC

**Comment by mdbs99** [comment] 2017-10-24 23:29
In time, I would say that I don't use the newest Delphi nowadays because its price. Yeah, it's insane.

I migrated from Delphi to Free Pascal / [Lazarus](http://www.lazarus-ide.org/) many years ago, but I still have some old projects that was coded in Delphi 7 (the most stable an classic version ever).

> There's Free Pascal. not sure how portability across versions is.

If would you like to take a look at Object Pascal, that is the way to do: [Free Pascal](https://freepascal.org/). It can compile in almost all OS, like C does.
There is a tool (well, there are others) to create bindings for C [here](http://wiki.freepascal.org/Creating_bindings_for_C_libraries).

A curiosity for you is that the compiler is coded in Pascal. The previous version compiles the new one.

Thanks for your time.
