### ISSUE TITLE
In push / pull mode, nanomsg support the maximum number of concurrent?

### ISSUE THREAD

**Issue by skyformat99** [nanomsg/nanomsg#836] opened 2016-11-23 02:10 UTC
Can support 100K concurrent access?
thanks

**Comment by gdamore** [comment] 2016-11-23 04:21
Generally not with a single system.  The reason is that you will run out of
TCP ports, even if you have enough CPU to make it work.

There may be some hacks that can be done to work around that, but honestly
I’ve never attempted to support such a vast number of concurrent user in a
single system.

You can build systems with nanomsg that support this using devices and a
“tree” approach, with each device supporting hundreds, or thousands, of
nodes at once.  However, if you have that many incoming requests (outgoing
is easier), it may be rather challenging.  For example, a single system is
probably going to struggle to cope with the load of a hundred thousand RPC
calls happening simultaenously, or to properly cope with survey responses
from this many nodes in response to a single survey request.

Essentially what I’m saying is, it depends on the pattern you choose.  But
no matter what you will be limited on TCP resources, and will need to scale
out some how.

**Comment by gdamore** [comment] 2016-11-23 06:04
This is a question, not a bug.   Closing.

**Closed by gdamore** 2016-11-23 06:04 UTC
