### ISSUE TITLE
peek a message

### ISSUE THREAD

**Issue by lab313ru** [nanomsg/nanomsg#881] opened 2017-05-11 09:42 UTC
Is it possible to receive a message without removing its data from socket? The same as recv with MSG_PEEK flag.

**Comment by gdamore** [comment] 2017-05-11 15:53
Sorry, but no, this is not possible.  Its possible we could add this; can you provide a little more data about your use case?

**Comment by lab313ru** [comment] 2017-05-11 16:18
For example you just want to check packet type. And if this packet should be parsed, you may read it. Else, you may leave it in socket so another thread will be able to read and parse that packet.

**Comment by itssofluffy** [comment] 2017-05-11 16:25
If we are looking at this would it also be possible to look at nn_poll and subscriber sockets, if a message is received that you are not subscribed to nn_poll will return a false positive (i.e. a message is waiting) but when nn_recv is executed it drops the message as it hasn't been subscribed too.

**Comment by reqshark** [comment] 2017-05-11 16:45
That's interesting to raise the idea of a nanomsg socket being compatible with a different socket protocol at the same endpoint address

**Comment by gdamore** [comment] 2017-05-12 20:28
I really think if you're "peeking" at messages you're doing something wrong from a design perspective.  Its better to use PUB/SUB, or different socket addresses.  With websocket you can even demux messages on the same port number (though you need to use mangos or write some custom code to do it -- which is on my TODO list).  So to justify MSG_PEEK, I'd really like a very concrete justification; the use case you've supplied just is too vague.

@itssofluffy  On the topic of nn_poll waking early, yeah, that's kind of unfortunate, but its an artifact of the underlying plumbing; we have to run the state machine and need the wakeup to get there, which means we need to run some code on the user thread.  It's also the case that there is no guarantee that nn_poll wakes up *only* when data is available; the guarantee is that we won't *fail* to wakeup when data is available.    But any rate thats a totally different issue from what is discussed in this bug.

@reqshark Sharing precise endpoint addresses for different protocols is *never* going to happen, because it turns out to be rather nonsensical to do so.  In fact, we don't tag every message with the protocol, its negotiated at connection establishment.  What you probably want is to be able to reuse the TCP port, which can be done with another qualifying element (such as a path component for a URI in websocket).    Allowing multiple protocols / sockets to share a single TCP port number is definitely in the cards; sharing the entire address is not.

**Comment by itssofluffy** [comment] 2017-05-12 23:03
@gdamore fair do's... as the base library author i was expecting exactly the answer you've given, but as an api writer the MSG_PEEK would provide me with a solution within my api to the false positive on nn_poll as you could check the subscription against your own internal list of subscriptions and drop the message if required.

**Comment by gdamore** [comment] 2017-05-12 23:13
Yes, I could.  The problem is that at present nn_poll doesn't know anything about the socket type.  It just knows that there is generically I/O ready.  Adding that knowledge at this stage in the game is not something I'd like to do, just to avoid introducing further complexity.

I will definitely keep this in mind for libnng -- in fact I think libnng already has the semantic you're looking for, since we aren't relying on the same underlying mechanisms for processing I/O. :-)

**Comment by reqshark** [comment] 2017-05-12 23:24
> What you probably want is to be able to reuse the TCP port, which can be done with another qualifying element (such as a path component for a URI in websocket). Allowing multiple protocols / sockets to share a single TCP port number is definitely in the cards; sharing the entire address is not.

@gdamore yea, that makes sense a lot more sense, I just thought that idea was interesting mostly out of curiosity, certainly not based on any real use case

**Comment by itssofluffy** [comment] 2017-05-12 23:32
No that's a good call, the base library on this type of function shouldn't have any kind of knowledge of the socket type that it's operating on, i have a solution in mind (from my api's point of view) to solve this issue, looking forward to the shape of things to come as in the shape of libnng!

**Comment by gdamore** [comment] 2017-10-11 17:44
This seems suitably resolved (answered) so closing it.

**Closed by gdamore** 2017-10-11 17:44 UTC
