### ISSUE TITLE
question：pub/sub

### ISSUE THREAD

**Issue by Slzde** [nanomsg/nanomsg#1011] opened 2018-12-12 07:23 UTC
i‘m so sadly i debug one day to it。

when i use pub/sub between process，and i send two string again and again but i only can recv only one all most。sometimes，it even looks random  ，for example ，i send “slzde” “slzde good” ，recv just “slzde” ，or recv “slzde” “slzde” “slzde good”，it must do not according to rule。
i ensure that i subscribe all the string ，and it is ok between thread ，i just change the addr to “ipc:///tmp/pubsub.ipc”

and i‘m so sorry that my english is very not good。

and thank you to read it 。

**Comment by Slzde** [comment] 2018-12-13 02:20
today，i find that if it nn_send without interval ，it will recv only one msg，it is a bug？ why ？ 

test between process  pub/sub

**Comment by Slzde** [comment] 2018-12-13 07:55
emmm。。i'm sorry to give you a bad experience.

and i will submit my general code

https://paste.ubuntu.com/p/SdCcNnqpfV/

maybe you should use VPN to visit the website. I don't know

**Comment by gdamore** [comment] 2018-12-13 10:15
So that example does not include any of the setup on the receiver side for Sub.

You are sleeping in your FuncRecv... don't do that.  Only the sender should sleep.  You want your receiver to run as fast as possible.

**Comment by Slzde** [comment] 2018-12-14 02:51
ok～  i get it。

thank you 。

I am sorry to disturb you. 

thanks  again，

**Comment by gdamore** [comment] 2018-12-14 05:08
So is it all working now?  Can I close this?

**Comment by Slzde** [comment] 2018-12-14 05:14
yes  thank you'

**Closed** 2018-12-14 06:52 UTC
Labels: awaiting feedback

**Comment by jed057** [comment] 2021-10-06 03:32
> So is it all working now? Can I close this?

hello sir, sorry to reply on a closed item but i apparently have encountered similar issue recently when using nanomsg in one of our project, i.e. we can see frequent packet lost in sub side when pub side sending msgs back to back (hundred microseconds to several milliseconds between each other, each packet size is about 200-300 bytes). 

the pub/sub are separated in 2 individual processes which running in a same Windows cloud server, when issue happen,
    - both ipc and tcp transport protocol have same symptom;
    - both blocking and non blocking (in both side) have same symptom;
    - add sleep in pub side and try not to sleep or lower loading in sub side could mitigate this issue ;
    - can't see this issue with better (cpu & memory) server;
    - can't see this issue with simple pubsub test project (without any application business logic or any other loading)
    - not tried in Linux server yet;

When issue happen, the nn_send always returns the sent bytes and the stats interface always returns expected msg delivery #. It looks everything is working fine however the missing one was always NOT shown in wireshark capture (tcp mode)

The issue is definitely NOT reproducible if changed pubsub to pipeline mode.

I have tried to read through the implementation differences between pipeline & pubsub but till now i can't fully understand the details. Meantime I noticed that you've mentioned pubsub is designed as best effort delivery only, so i wonder what about pipeline mode, is it designed as delivery guaranteed? In general I want to make all the observations above explainable.

Looking forward your kind reply and really appreciate it. :)

**Comment by gdamore** [comment] 2021-10-06 14:41
If you can’t consume packets fast enough on the subscriber side then the publisher will drop them.  This happens before the message is sent over the transport. (Basically when the transport says it cannot take any more the pub socket drops.) This behavior is unavoidable with any broadcast type protocol. (Unless you’re willing to block the sender for all subscribers or are able to provide infinite memory for queuing and don’t care about latency.)

Essentially your subscriber cannot keep up with your publisher.

Pipeline is 1:1 for a given message and so does not behave this way.  It will block until the message can be accepted. It is not perfectly reliable but it isn’t subject to drops because of load.

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by jed057** [comment] 2021-10-07 02:39
> If you can’t consume packets fast enough on the subscriber side then the publisher will drop them...

Thanks very much for your reply, its really helpful! I just wonder when the said scenario happen is there any means for pub being aware of it? or has to be the sub to resp some "ack" then the pub can know that?

besides, when you say the pipeline is not perfectly reliable, is there any typical case which could cause the drop in this mode? we are using this between processes within a single server, need to evaluate the possibility of this case.

**Comment by gdamore** [comment] 2021-10-07 04:16
Without a device in the middle and assuming a stable connection pipeline won't drop messages. It's when the connection is lost or broken that messages can get lost. 

There isn't really anything you can do easily about pub/sub being lossy under load. The only way to fix that is to use a scheme such as using sequence numbers, periodic broadcasts, and a req/rep back channel to fill in missed messages. That is a little bit of effort and probably for your use case using pipeline is sufficient and lots easier.
