### ISSUE TITLE
Why use CMake for Windows only ?

### ISSUE THREAD

**Issue by rcari** [nanomsg/nanomsg#210] opened 2013-12-24 01:14 UTC
Why not use CMake for all builds ? Including UNIXes ?

**Comment by photex** [comment] 2015-02-23 16:06
Late to the party here, but CMake makes it very easy to automatically include a library as an external project. It's also a build system supported by several IDEs directly.
So I just wanted to toss a +1 in here in favor of supporting CMake officially again. 
I don't exactly like using it, but it's had a net positive impact on my work. I understand the arguments for autotools in regards to the interests of package maintainers, but I've never worked someplace that didn't require managing specific versions of packages for our builds independently of a platforms available packages. For this CMake is very well suited.

**Comment by madscientist42** [comment] 2015-02-23 21:56
Autotools isn't exactly designed for what we're talking about her.  It's
designed to fix the GNU's perceived problems.  (Namely trying to build on a
bunch of *VERY* old, *VERY* broken compilers and system libraries- which,
while laudable, is a QUESTIONABLE concern these days...)  And then, the FSF
thought it was the greatest thing since sliced bread and that everyone and
his dog should use it.  It is less useful for the problems that most
developers face.

I'm like you.  I don't exactly like it either, but I **really** dislike
Autotools.  Rather than boring the discussion here, I'll give my rant on
StackOverflow:

http://stackoverflow.com/questions/4071880/autotools-vs-cmake-vs-scons/18291580#18291580

I'll not walk away if the project keeps Autotools- but I *WILL* rib the
hell out of the lot and tell you I told you so if you do and you manage to
break cross-compilation in the process...   >;-D

This is not just for Windows.  But for ARM, MIPS, and the like- not
everything in that space is beefy enough to do host compilation and not
everything (not even close) that at least this library would be for is
going to be sitting on X86.  Everyone that is for Autotools has never had
to maintain the damned thing on a complex project, or try to make it play
right on a cross-compilation.  Scratchbox/Scratchbox2 was commissioned by
Nokia for Maemo to compensate for the problem I talk to in the rant and
here.  CMake was developed to replace Autotools for those reasons.  (For
the record, I have had to sort out all sorts of screwed up on Autotools on
numerous projects- a solid third of the projects do not properly care or
watch for stupid things that cause you to pop right out of the
cross-compile sandbox.)  I wrote that rant when I was trying to make Thrift
compile in OpenEmbedded so I could add it to a target's SDK for a client.
Had to discard it and go with something else because it just was too much
pain to FIX the blasted Autotools scripting because it was everywhere and
made blind assumptions to /usr/... and the like.  It's easy to make these
mistakes because you're using a twisted mix of M4 macros and bash scripting
to do the load lifting on everything.  That's why I really dislike it
everywhere I go.  At least with CMake, I can readily make it behave without
Scratchbox and expect 99% of the projects that used it to have largely
gotten it "right" for cross-compilation under any context.

**Comment by lu-zero** [comment] 2015-02-23 22:39
No, false totally and egregiously false.

in autotools you have

```
./configure --host=$CHOST
```
And if the people writing the configure script didn't do something stupid (can happen I know quite well) everything ends here.

in cmake, **now** (before was even worse) you have to create a spec file for every toolchain you want to use and yet hope that something stupid hadn't been done (again, can happen, even more often).

Gentoo crossdev works perfectly with autotooled packages while the cmake-based ones tend to break in quite amazing way even if now the toolchain specifications are generated.

The things you might have to take care of are:
- bogus pkgconf files (and it is the same for both cmake and autotools)
- faulty linker scripts (some packages do install them)

That said for the scope of a C project that is lightweight as nanomsg, cmake remains a huge dependency, autotools releases do not require autotools but just a shell and make.

**Comment by photex** [comment] 2015-02-23 22:44
Why can't nanomsg just use both? I'd wager there are enough willing volunteers to maintain them equally well.

**Comment by snikulov** [comment] 2015-02-24 09:58
@sustrik Can we merge my branch with cmake into mainline? It will be easy to keep it in sync. Then we'll close this issue.

**Comment by javalama** [comment] 2015-03-09 15:11
On a related note, git head doesn't compile on OS X maverick, auto tools is installed.

Makefile.am:46: error: Libtool library used but 'LIBTOOL' is undefined

**Comment by glycerine** [comment] 2015-03-24 16:02
@javalama : I don't think maverick ships with gnu libtool, only Apple libtool, so some macros are missing. "brew install libtool" usually fixes this for me.

**Comment by gddg** [comment] 2015-03-25 13:48
I successfully build  nanomsg  . 

first step : 
brew install libtool 
brew install autoconf
brew install automake
-------------------------------------
second step : check build system 

glibtool --help

When reporting a bug, please describe a test case to reproduce it and
include the following information:

       host-triplet:   x86_64-apple-darwin14.1.0
       shell:          /bin/sh
       compiler:       clang
       compiler flags: -g -O2
       linker:         /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld (gnu? no)
       version:        glibtool (GNU libtool) 2.4.5
       automake:       automake (GNU automake) 1.15
       autoconf:       autoconf (GNU Autoconf) 2.69
--------------------------------------------------------------------------------------
ok follow the << Build it >>

**Comment by javalama** [comment] 2015-03-25 16:38
i followed those steps, same problem. then i found some receipt doing some glibtoolize magic, and i somehow got it work. dunno how. this build system is shit.

**Comment by gddg** [comment] 2015-03-26 12:49
install  xcode command  
brew install libtool 
brew install autoconf
brew install automake
glibtool --help
sh autogen.sh
 ./configure
make
make check

**Comment by gdamore** [comment] 2015-03-30 03:39
Holy smokes! I've done the initial work to convert to cmake.  Maybe I'll revisit this soon.  If we switch to Cmake, it will be a *switch*.  I have no interest in working in *two* different build/configuration environments.

**Comment by javalama** [comment] 2015-04-02 20:42
@gdamore Awesome - keep it up :) I hate the current build system.

**Comment by atif1996** [comment] 2015-04-29 22:47
I'd love to help keep the cmake build system up to date, if you guys decide to go that route.  I work on a product that targets Mac OS and Windows, and CMake was a god send for us.

**Comment by gdamore** [comment] 2015-04-30 00:05
Thanks.  I’ll probably have some time to finish up my work here in the next week or two.  I’ve been busy on other things lately…

	- Garrett

**Comment by gdamore** [comment] 2015-10-26 00:40
I'm abandoning that effort; frankly its more work than its worth for this edition of libnanomsg.  Any future rewrite will probably use CMake exclusively, but for now, autotools work.

**Closed by gdamore** 2015-10-26 00:40 UTC

**Comment by javalama** [comment] 2015-10-26 21:30
Very sad to learn this effort is abandoned. Building nanomsg on certain OSX versions is nearly impossible.

Sigh.

**Comment by gdamore** [comment] 2015-10-26 22:32
Why?   Should be able to just download the distro then ./configure && make install. 

Building from git may be harder but those are devel releases.

**Comment by photex** [comment] 2015-11-11 11:21
Big sad face for closing this. CMake makes building and using nanomsg worlds easier.

**Comment by wirebirdlabs** [comment] 2015-12-11 17:33
I've begun to work on this with intention to upstream. Can we re-open this case? (or shall I create a new one?)

Also; is it worthwhile to open issues for loose-ends found in the build process while working on this?

For instance: the declaration of `NN_USE_EVENTFD` versus `NN_HAVE_EVENTFD` compared with their later use in the source files.

One might consider that `NN_USE_EVENTFD` is the one driving the `#ifdef` in code -- but indeed it's `NN_HAVE_EVENTFD`, while `NN_USE_EVENTFD` remains unused after being set in the autotools `configure.ac` script.

A related consideration is the order of precedence in which these different options are chosen. Should this be done by the configure file, or the source file?

The autotools script prefers eventfd over pipe over socketpair: https://github.com/nanomsg/nanomsg/blob/86bc0c89957ce5c08a83179f0645dbff7b64e97a/configure.ac#L359-L367

The code agrees: https://github.com/nanomsg/nanomsg/blob/10a567c89e564def7f5ae01f8c3bb1dab2acfed5/src/utils/efd.c#L28-L33

Whereas when choosing socket mulplexing strategy in the configure file: https://github.com/nanomsg/nanomsg/blob/86bc0c89957ce5c08a83179f0645dbff7b64e97a/configure.ac#L296-L300

The order of precedence is different in source: https://github.com/nanomsg/nanomsg/blob/9a0cb281695759fde449244b5f664ece5075d9f5/src/aio/poller.c#L27-L33

For clarity -- these aren't bugs, just inconsistencies that probably arose over time.

**Comment by wirebirdlabs** [comment] 2015-12-14 02:16
Continued here: #574
