### ISSUE TITLE
First message is lost sometimes in Push/Pull transmission

### ISSUE THREAD

**Issue by vlisivka** [nanomsg/nanomsg#1005] opened 2018-11-14 13:56 UTC
When connection is established from Push socket to Pull socket and then message is sent, sometimes message is lost in transition. 

Test case using nanocat: [test-nanomsg-first-msg-lost-bug.sh.gz](https://github.com/nanomsg/nanomsg/files/2580975/test-nanomsg-first-msg-lost-bug.sh.gz)

Expected result: 100 messages delivered. Actual result: 62-99 messages delivered.

Checked on Fedora 26-28, custom Yocto distro, MacOSX.

**Comment by SG7** [comment] 2018-11-14 14:03
Introduce a small delay (10-100 ms) after opening the port and see if
problem goes away.

**Comment by vlisivka** [comment] 2018-11-14 14:41
Small delay (5, 10, 50, 500ms) makes no difference in loss ratio.

**Comment by gdamore** [comment] 2018-11-14 15:40
Can you post a reproduction case?

**Comment by vlisivka** [comment] 2018-11-14 17:03
@gdamore I already posted test case with nanocat. This bug is hard to reproduce. I'm lucky that I can reproduce it using nanocat.

**Comment by vlisivka** [comment] 2018-11-14 18:03
I noticed that variant with nanocat does not trigger problem on Yocto/armv7 with custom kernel right now. Test case triggers problem on Fedora-28 and MacOS El Capitan. I'm surprised, because we found this problem on Yocto, but I was unable to reproduce it on Fedora using C code.

**Comment by gdamore** [comment] 2018-11-22 04:30
You should add --delay <SEC> (say "1") to your nanocat invocation that sends the data.  This inserts a delay before sending, to allow the connection to be established.

This is necessary because on some systems the connection might take a little bit to establish.  This is highly dependent on the kernel, C library, number of CPU cores, and transport.    Adding the delay gives the stuff a chance to settle down.

(You can probably delete your sleep 0.1 though.  That sleep does no good, because it happens before the attempt to establish an outgoing connection is made, and thus is too early.  The only way to do this correctly at the command line is to use the -d (or --delay) command line.

**Comment by gdamore** [comment] 2018-11-22 04:32
So this isn't a bug, per se, although the behavior is somewhat unfortunate.  NNG can wait to establishe the connection by default (although I'm not sure that is exposed in nngcat -- I'll have to check to be sure.)

At any rate, I am going to close this as it's not a bug in nanomsg itself.

**Closed by gdamore** 2018-11-22 04:32 UTC

**Comment by vlisivka** [comment] 2018-11-22 10:57
When --delay 1 option is added, nanocat hangs on 2-4 invocation:
`[vlisivka@apollo5 download]$ ./test-nanomsg-first-msg-lost-bug.sh
+ (( I=0 ))
+ (( I<100 ))
+ nanocat --push --connect-ipc /tmp/pull-socket.ipc --data 123456 --delay 1
+ (( I++ ))
+ (( I<100 ))
+ nanocat --push --connect-ipc /tmp/pull-socket.ipc --data 123456 --delay 1
+ (( I++ ))
+ (( I<100 ))
+ nanocat --push --connect-ipc /tmp/pull-socket.ipc --data 123456 --delay 1
+ (( I++ ))
+ (( I<100 ))
+ nanocat --push --connect-ipc /tmp/pull-socket.ipc --data 123456 --delay 1
c^C
[vlisivka@apollo5 download]$ ./test-nanomsg-first-msg-lost-bug.sh
+ (( I=0 ))
+ (( I<100 ))
+ nanocat --push --connect-ipc /tmp/pull-socket.ipc --data 123456 --delay 1
+ (( I++ ))
+ (( I<100 ))
+ nanocat --push --connect-ipc /tmp/pull-socket.ipc --data 123456 --delay 1
^C
[vlisivka@apollo5 download]$ ./test-nanomsg-first-msg-lost-bug.sh
+ (( I=0 ))
+ (( I<100 ))
+ nanocat --push --connect-ipc /tmp/pull-socket.ipc --data 123456 --delay 1
+ (( I++ ))
+ (( I<100 ))
+ nanocat --push --connect-ipc /tmp/pull-socket.ipc --data 123456 --delay 1
+ (( I++ ))
+ (( I<100 ))
+ nanocat --push --connect-ipc /tmp/pull-socket.ipc --data 123456 --delay 1
^C
`

**Comment by gdamore** [comment] 2018-11-22 16:04
You need to change the value of ${TIMEOUT} in your script too.  I'm running it now with just setting TIMEOUT to 200 and adding -d 1 and it's fine.

The unfortunate aspect of your script is that all these are run serially -- maybe you meant to run them in parallel instead?

You do have other errors in your script.  For example, the receive timeout is not working because you have the redirect to a file after passing those arguments.

The following diffs resolved it correctly for me, with the entire set of pushes running in parallel in the background:

```
bash-3.2$ diff -u /tmp/to.sh /tmp/tn.sh
--- /tmp/to.sh	2018-11-22 08:03:09.000000000 -0800
+++ /tmp/tn.sh	2018-11-22 08:02:32.000000000 -0800
@@ -4,13 +4,14 @@

 # Run nanocat in background, to dump incomming packages into log, and exit after 3 seconds
 killall nanocat 2>/dev/null
-( nanocat --pull --bind-ipc /tmp/pull-socket.ipc --quoted > /tmp/pull-socket.log --recv-timeout $TIMEOUT ) &
+( nanocat --pull --bind-ipc /tmp/pull-socket.ipc --quoted --recv-timeout $TIMEOUT ) &
 sleep 0.1

 # Send 100 nanomsg messages
 for((I=0; I<100; I++))
 do
-  nanocat --push --connect-ipc /tmp/pull-socket.ipc --data "123456"
+ echo "I is ${I}"
+  nanocat --push -d 1 --connect-ipc /tmp/pull-socket.ipc --data "123456" &
 done

 (( $SECONDS < $TIMEOUT )) || {
@@ -18,8 +19,10 @@
   exit 2
 }

+echo "Waiting..."
 # Wait for background job to finish
 wait
+echo "done."

 # Count of number of lines in log
 NUM_EVENTS=$(wc -l </tmp/pull-socket.log)
bash-3.2$
```

**Comment by vlisivka** [comment] 2018-11-22 18:57
First, to clarify, I'm professional developer with 20 years of experience. I completed more than 30 projects and used more than 20 languages over two decades. I'm PhD in Computer Science. Blah blah blah. I just trying to say that I'm experienced enough.

I this test case, I'm not trying to test nanomsg under high load. I'm just trying to catch rare bug, so I need to do lot of repetitions.

I tried `--delay 1` option at work, and nanocat hanged at 10th call. I killed it, then installed nanocat-debuginfo and nanocat-debugsource packages to debug nanocat with gdb. Unfortunately, I'm unable reproduce this hang after 3+ thousands of repetitions, while I was able to reproduce it at home 3 times in a row. I use Fedora 28 both at home and at work. I will try to reproduce problem again. Hangs are easier to debug than random message drops.

As I see, `--delay 1` option does not help me: only about 80% of first messages are delivered at average.

I suspect "use of uninitialized value" bug, compiler optimizer bug, or kernel bug (e.g. recent fixes for Meltdown). I will try to find source of this bug when I will have free time because it affects me.

`--receive-timeout` option for listening nanocat is added for clean shutdown of nanocat. It can be removed and nanocat can be killed instead, so `TIMEOUT` variable will be unnecessary. However, good test case should be clean, without killing of processes, because it will test abnormal path instead of normal path of work.

**Comment by gdamore** [comment] 2018-11-22 19:55
This isn't about how much experience you have.  Its specifically about the problems with the script, and misunderstandings about how this software is meant to work.

(I might not have a PhD, but I've well more than 20 years of experience, a number of them with this particular software, and have produced probably several millions lines of code across many software packages, some of them quite famous open source ones.  Google me if you want to know more.  I don't particularly find any of this relevant to this particular conversation, but as you seemed to wanted to measure egos... there you go.  Oh, and I'm sorry to inform you of this, but I've found very little correlation between possession of a PhD and actual practical implementation ability.  If there is a correlation, it's probably the inverse of what you think it is.  Theory and practice are quite often pretty far divorced from each other.)

At any rate, your script has certain bugs.  I was able to fix the script, and I posted the updates to you.  Did you try them out?  Did you try to understand them?

Specifically you need to understand about something called "slow start", where its nanomsg does connection management in the background.  If you're used to synchronous connect behaviors, this can be quite surprising.  Hence the need to add the --delay field.  This lets the connection be fully established before you start sending data.

**Comment by vlisivka** [comment] 2018-11-22 21:51
I know who you are, and I respect your work. It's why I'm asking for your help. I just trying to say that you can trust me when I say that test script works as intended and contains no errors.

I tried to use valgrind, ltrace, strace with following results:

  * when nanocat client is ran under valgrind, no errors are found and 100% of messages are delivered each time.
  * under ltrace and strace, 96-100% of messages are delivered, i.e. error rate drops by order of magnitude.

I modified test script to catch missed message early and stop, so I can inspect output of ltrace and strace. 

I see no deviations in `ltrace -f` output for both cases, when message delivered and when it's not.

Output of `strace -f` for nanocat client  is long and interleaved, but, as I see, all reads and writes are ended successfully in both cases, so data is transmitted to pipe.

I will try more tools tomorrow.

Currently, I suspect that it may be caused by time adjusting (maybe I have very bad HW clock which need constant adjustments?), so it may affect clock_gettime(). I will try to use Linux specific clock, e.g. CLOCK_MONOTONIC_RAW or CLOCK_BOOTTIME.

**Comment by gdamore** [comment] 2018-11-22 23:04
I'm telling you the script you sent me had serious errors, which I fixed and sent you the fixes for.  If you're unwilling to consider that possibility, then I don't really see much good coming from further interaction.

If you do find a real bug, please let me know with a reproduction case.  I can't promise I'll agree with you, but I do promise to at least look at it and see if it's a real issue.

For the issue reported here, I don't see any problems once the script is fixed -- I was able to run the program to a clean conclusion with all 100 messages received without any losses in just a couple of seconds.  Without those fixes, the program didn't work at all, and did in fact appear to hang (as you indicated).
