### ISSUE TITLE
Push/pull over IPC loses a lot of messages

### ISSUE THREAD

**Issue by Chasx** [nanomsg/nanomsg#690] opened 2016-05-06 14:33 UTC
I am in the process of deciding between a couple of messaging frameworks. My particular situation would contain a lot of 'workers' that send their information to one 'chief'. I think push/pull is most suitable for that.

I made a test program over IPC but it fails often so I tried nanocat to do the same but that also fails:

* In one terminal screen I start "nanocat --pull -X /tmp/pipeline.ipc -A"
* In another terminal I run "echo test | nanocat --push -x /tmp/pipeline.ipc -F-"

By just firing the second command a couple of times the 'test' message is sometimes not shown on the first terminal. I think about about 30-40% of the sent messages are not arrived. If I switch to TCP instead of IPC the problem does not occur (or at least not so very often as it is here).

Am I doing something wrong? Is this expected behaviour? I am running nanomsg 0.8 on Linux Mint (Ubuntu 14.04).

Ultimately I would have like to use nanomsg (or something else) to solve producer consumer problems and a couple of other messaging patterns.

**Comment by gdamore** [comment] 2016-05-06 14:38
The problem is lack of linger.  Your program (nanocat in this case) is exiting before the message is fully delivered. IPC doesn't have a linger but TCP does.

**Comment by Chasx** [comment] 2016-05-06 15:24
Ok, and what is the best way to fix this? I tried the first example (pipeline) on http://tim.dysinger.net/posts/2013-09-16-getting-started-with-nanomsg.html and this also shows the problem when starting a couple of 'node1's'. Would it suffice to just add a 'sleep' before 'return nn_shutdown (sock, 0);' or is there a better way?

**Comment by Snaipe** [comment] 2016-05-06 15:40
I am in a similar situation. What I did was to setup a reverse REQ/REP (The server is REP, the workers are REQ). When a worker has information to communicate upstream, it sends a message to the server, and the server responds with some kind of ACK message (Either OK or an error status). This solves the problem of lingering regardless of the transport and has the advantage of providing basic error handling.

**Comment by gdamore** [comment] 2016-05-06 16:25
Sleep is probably sufficient.  Short of acking the data (eg via req rep) there isn't much else you can do.

**Comment by gdamore** [comment] 2016-05-06 16:25
Yes if you can do this having the ack is a definite win. :)

**Comment by gdamore** [comment] 2016-05-09 16:13
Closing; not a bug.

**Closed by gdamore** 2016-05-09 16:13 UTC
