### ISSUE TITLE
Lot of message lost in IPC

### ISSUE THREAD

**Issue by bizzard4** [nanomsg/nanomsg#824] opened 2016-10-21 21:32 UTC
Messages get lost when a lot of them are send. I use PUSH/PULL IPC with blocking call.

My code : https://gist.github.com/bizzard4/a1337ffac3dc2485b4fecf760a117a27

I can have multiple sender, but I can provoke the issue with a single sender.
Reproduction : 
1) start server : nano_ipc 1 1000 10 s ipc:///tmp/test_2
2) start client nano_ipc 1 1000 10 c ipc:///tmp/test_2
This will make the client send 1000 "data" message to server. # of packet lost depend on the run. If I add a small sleep in the sender it will work, but then if I add more sender eventually it will stop working again.

The same code in TCP will work. For example, with 100 senders and 1 server, I see that the server struggles to get all messages, but all senders are blocked and properly wait to send the message. In IPC, message seem to be "send", but receiver lose the track of it. I am not sure if the problem is on receiver or sender side.

**Comment by gdamore** [comment] 2016-10-25 03:38
On MacOS X, this does not reproduce.

**Comment by gdamore** [comment] 2016-10-25 03:44
Hmm... I have a theory.

If you're exiting the sending application too soon, the messages might be lost in a kernel write buffer.  TCP has a special socket option (LINGER) to deal with this, but IPC does not.  The thing is that depending on the implementation of the sender... the socket may fail to deliver buffered messages.  I'm also looking at your code now.

**Comment by gdamore** [comment] 2016-10-25 03:52
What platform are you running this on?  Apart from the possible lost message from shutdown, I cannot reproduce this on MacOS X.   I've run up to 16 concurrent threads, and no lost messages.

**Comment by bizzard4** [comment] 2016-10-25 19:45
I can reproduce very easily on my VM using Ubuntu 16.04 same on my t2.small Amazon Ubuntu machine.

Now if I add a small sleep(1) just before shutdown it seem to make thing work. That would fit with what you said, because my process was exiting just after sending. I can use this as a temporary workaround for my measurement. 

In a real scenario, I guess it would be possible to implement a simple solution to that.

**Comment by bizzard4** [comment] 2016-10-25 22:26
Also, my code using only Unix domain socket worker properly. The only difference is that the socket is created using blocking. While in nanomsg socket is created non-blocking.

**Comment by gdamore** [comment] 2016-11-23 01:57
I'm fairly confident that what is happening is that messages are lost here on exit.   The non-blocking mode means that the message can be queued in the library, which may mean that the message is lost (or incomplete/partially written) where blocking would mean that you don't return until the message is fully written to the pipe.

Using IPC, its imperative you don't exit immediately after writing to the IPC, if you care about the delivery of the data, because unless the data is acked you won't know if it got there.  The short delay prior to exit is generally enough to take care of it -- even just a few milliseconds is plenty unless the reader on the other side is slow.

I'm going to close this, because this is an architectural consideration of UNIX sockets, and there isn't really anything I can do to "fix" it.   It's incumbent on the API consumer to give time for full message delivery.

**Closed by gdamore** 2016-11-23 01:57 UTC
Labels: awaiting feedback
