### ISSUE TITLE
High CPU usage and memory leak

### ISSUE THREAD

**Issue by rty813** [nanomsg/nanomsg#1072] opened 2022-01-28 03:41 UTC
When I use the pynng module, there will be occasional memory leaks, the available memory will gradually decrease, and the CPU usage will reach more than 120%. Since my program is more complicated, I'm not sure if it's a problem with the pynng module, or something else. So I want to ask, is there any way to troubleshoot?

There are some logcat screenshot.

1. lsof
![e06d2d7f99a1fd4d06642fa48749213](https://user-images.githubusercontent.com/22488813/151483299-b8ce6316-22cf-49a6-a1ef-c9bc91a23b24.png)

2. strace (9742 is the problematic process)
![4ab9b2a9d415eacb7833808b076755b](https://user-images.githubusercontent.com/22488813/151483308-703a2cb7-f201-45a9-b531-d81619b9855b.png)

3. top -c
![image](https://user-images.githubusercontent.com/22488813/151484163-391ba202-e541-449b-b619-eed59e3c593e.png)

4. mem_avail
![1643342449(1)](https://user-images.githubusercontent.com/22488813/151485157-1d3d4284-18c8-42ff-8a2d-267ef7065357.jpg)

**Comment by gdamore** [comment] 2022-04-18 23:09
This is a duplicate of another issue filed against NNG.

**Closed by gdamore** 2022-04-18 23:09 UTC
