### ISSUE TITLE
inproc not MT safe

### ISSUE THREAD

**Issue by BTCDDev** [nanomsg/nanomsg#429] opened 2015-06-20 19:11 UTC
Hi,

I am working on porting an application from Unix to Windows using MinGW. I am cross compiling nanomsg with MXE on Ubuntu. 

I have built the simple documentation pubsub/pipeline projects this way, and they work well on Windows.

However, the project I am working on is doing intensive polling and some multithreading.

Every time nn_send it called, it returns EAGAIN (Resource unavailable). I have tried setting it to retry, and putting sleeps before it. Neither works.

The only thing that did work was changing the last argument of select() in nn_efd_wait() to NULL (always block until ready). This works, but causes other errors later.

**Comment by reqshark** [comment] 2015-07-12 03:34
@BTCDDev if MinGW supports kernel multiplexing strategies or anything else vicinity that aligns with POSIX syscalls and the windows detection mechanisms in nanomsg attempt to employ winsock equivalent operations I could imagine unpredictable results in that environment. 

I am curious about other people's experience attempting to combine MinGW with nanomsg.

unfortunately i don't understand enough low level windows system to provide a more helpful response here. personally, I can just say when programming for windows I try to stick to the windows compilers microsoft recommends using like the community edition visual studio. usually nanomsg works pretty well there, at least the beta-5 tag has been stable. 

Also I'm not really sure where things are with master branch and windows

**Comment by gdamore** [comment] 2015-07-22 20:32
I need to do some testing with MinGW.  I don't have a good feeling about it at present.  But the stock Windows port seems to work ok.   At least I was able to get it to pass test suites on AppVeyor.

I'll take a closer look at MinGW later.

**Comment by gdamore** [comment] 2015-10-21 22:20
Question: can you build the test suite with MinGW, and if so, does it pass?  If it does, then it should be fine and the problem may be in assumptions you're making in your application.  If it doesn't, that 's another problem.

**Comment by gdamore** [comment] 2015-10-22 22:52
Btw, inproc has lots and lots of problems in multithreaded environments.  I *strongly* discourage its use in those environments at present.  "Fixing" it is a bigger challenge than you think, but I hope to do so at some point.

**Comment by gdamore** [comment] 2015-10-24 16:41
Old title: MinGW inproc multithreaded -- nn_send always returns EAGAIN

**Comment by gdamore** [comment] 2016-05-26 19:58
I may need to reevaluate this bug.  I think inproc isn't nearly as bad as I first believed, because there is a context for the socket, and only a single worker thread.  The issue is ensuring that the various global entry points acquire this mutex, and that the work calls the functions in the FSM with the same ownership held.  I'm not 100% sure that this is the case -- its really tricky to follow through all the transitions.

There's a lot here to do.

**Comment by gdamore** [comment] 2017-10-11 19:46
I'm abandoning the legacy inproc optimization.  I will be redesigning the transport to use socketpair and/or TCP loopback (Windows).  This will mean that inproc isn't as fast as we would like, but it will at least be threadsafe.

The nng library contains a safe, optimized, inproc transport, that I recommend if you need such functionality.

**Comment by gdamore** [comment] 2017-10-12 23:40
Well, there are some unfortunate things if I go down that road -- I had a separate thread which did the connects, but this caused a delay in setting up the connections (much like TCP has btw), which broke a bunch of test programs which assumed connections were immediately available. 

Looking at it more now --  I've got my head around the contexts a bit more, so maybe I can actually make this work...

**Comment by gdamore** [comment] 2017-10-13 00:21
I do think there is a potential inproc issue remaining, but some of the tests were in the test programs, which are about to be resolved.

I'm less convinced that we have a reproducible issue  -- but I can see a potential issue with the locking involving multiple sockets and nn_fsm_raiseto().  Its possible that a solution is to use a single monster lock for all contexts.  That would mean potentially less parallelism, but really we have only a single worker thread for the entire nanomsg system, so this isn't that big a deal.

The new nng rewrite is far more scalable in this regard.

**Comment by gdamore** [comment] 2017-10-13 00:30
So the main thread safety issue is in crossing between FSMs for different sockets.  Having said that, we do have a problem with the pushing of the messages from one FSM to another if that first FSM goes away.  I'm concerned that we don't discard a sinproc until the peer's FSM has indicated it is done.

**Comment by gdamore** [comment] 2017-10-13 00:32
Ok, this all looks good now... I am going to close this issue -- once the inproc tests are fixed (issue reopened), the actual concerns about thread safety are done.

**Closed by gdamore** 2017-10-13 00:32 UTC
Labels: release-stopper
