### ISSUE TITLE
nn_bind does not fail when binding to an already bound TCP port

### ISSUE THREAD

**Issue by saulthu** [nanomsg/nanomsg#617] opened 2016-04-07 08:13 UTC
I'm running on Win10 and using the master branch at 8f873b4, 4 Feb. Stepping through code shows the second bind failing at usock_win.inc:239 in nn_usock_bind(), but the error never reaches the return value of the public API nn_bind().

**Comment by gdamore** [comment] 2016-04-12 18:21
That's normal, and somewhat unfortunate.  The code assumes that it will keep retrying the bind, and the application is insulated from the failure.  This is symmetric to nn_connect() failing.  Arguably in the nn_bind() case we could (should?) be able to report errors back up -- although its still the case that such errors may be temporary.

Adding a wrinkle here, the actual socket shouldn't see failures from a single nn_bind failing, since you can have multiple transports in use, and one pipe failing doesn't necessarily impact the others.

**Comment by JackDunaway** [comment] 2016-04-12 18:53
Even though this issue describes intended behavior, it is one behavior that I would also like to see changed. We should keep this issue open, rather than closing it as "works as intended".

I understand the rationale of the current behavior -- it's in line with the nature of the asynchronous try and retry to bind -- but it might be worthwhile to treat the very first bind as "special", and perform logic within `nn_bind()` on basic sanity checks such as this issue. I might even lean so far as wanting to block within `nn_bind()` until the first bind is successful (or providing a new such function, such as `nn_bind_synchronous()`), after which point the existing behavior of `nn_bind()` (and `nn_connect()`) continues.

**Comment by reqshark** [comment] 2016-04-12 18:58
> might even lean so far as wanting to block within nn_bind()

+1, optionally blocking bind and connect calls for TCP would be nice

**Comment by saulthu** [comment] 2016-04-13 00:14
+1, optional synchronous bind/connect would be helpful in my case

**Comment by gdamore** [comment] 2016-04-13 01:04
I'd make this instead just a synchronous nn_bind() by default.  There is no reason really to have to retry, etc. because unlike nn_connect() this is entirely determined at start time, and should never fail afterwards.  We can add an nn_connect_async() option after.

**Comment by JackDunaway** [comment] 2016-04-13 02:01
Another welcome side effect of this would be the ease of binding to an ephemeral port, which has so far been another explicit non-goal of nanomsg. 

The main rationale of this being a non-goal, as I understand, is that distributed service discovery is more challenging, if not impossible. This rationale is valid for many application domains, but I work in at least one domain -- embedded software -- where ephemeral ports would solve some actual pain points. Sure, ephemeral ports are not directly related to the discussion of this issue ... but a synchronous bind is perhaps the only major technical gate for a sane ephemeral port support.

**Comment by gdamore** [comment] 2016-04-13 02:16
Ephermal port binding is useful, provided you have an out-of-band way to get information about the service address.  So you'd like to get back (or have a way to get back) what the actual port is, which then could be either displayed to the user, or passed to some other components.  One example I've used in the past is to actually use this to register a service with a task manager/directory using the SURVEYOR pattern.

That is, we have a service that sets up a REP socket on ephemeral port X.  It then gives this port X in an application specific message that is delivered to the manager via SURVEYOR.

This could be done on the same host, to, using other notification methods.  The usage scenario is very much like rpcbind.

All this notwithstanding, I am convinced that nn_bind() should be synchronous by default.  Even with ephemeral ports this works, because you should get *some* port by default, without blocking for an inordinate amount of time.

To be honest, I'm having a hard time understanding the use case for an asynchronous nn_bind, even though that is what we have today.

**Comment by JackDunaway** [comment] 2016-04-13 03:15
> provided you have an out-of-band way to get information about the service address

Exactly. This constraint can hold well in embedded system design, and even turns out to be more desirable oftentimes (that's just a personal contention), compared to, say, the application space of physically distributed IP networks and the internet.

> having a hard time understanding the use case for an asynchronous nn_bind

After a brief research, one error that `bind(2)` returns synchronously that libnanomsg might eventually overcome with retries is `ENOMEM`

But that's the type of situation where libnanomsg is probably not going to end up being successful anyway ... it'd be better not to queue up a retry. The application is sick, and libnanomsg retrying is only going to make things worse.

The other situation that could be "fixed" after retrying is the one reported in this issue -- `EADDRINUSE`.

Yet, this is the type of error that most likely is an application design flaw, where libnanomsg would serve the application developer better to throw an error.

Most other errors for `bind(2)` are synchronous errors with parameter problems -- meaning, passing the same parameters will throw the same errors, where it would have been better to fail with error on the first such try.

So ... I think I agree, it makes sense for `nn_bind()` to be unconditionally synchronous.

That said, we'd need to thoroughly research whether name resolution (or other things) provide value for `nn_bind()` being async.

And to stress: these considerations are only for `nn_bind()` only, not `nn_connect()`, since preconditions on these endpoint roles are not symmetrical.

**Comment by JackDunaway** [comment] 2016-04-13 03:19
Another positive side-effect of a synchronous bind could be, ironically, better performance: https://github.com/nanomsg/nanomsg/blob/master/tests/tcp.c#L214-L215

**Comment by gdamore** [comment] 2016-05-11 21:51
Marking this one for 1.0 milestone.

**Closed** 2016-06-01 02:36 UTC
Labels: release-stopper
