### ISSUE TITLE
nanomsg errors during perf testing

### ISSUE THREAD

**Issue by AlexanderZh** [nanomsg/nanomsg#599] opened 2016-01-31 14:55 UTC
The following errors happen for executables in perf directory:

1.  If **inproc_thr** is launched several times without any delay from terminal it finally hangs up. Placing for loop inside **inproc_thr.c** makes this problem reproducible. Placing _printf_ both into _void worker (NN_UNUSED void *arg)_ and _int main (int argc, char *argv [])_ helps to figure out that some messages are lost during _inproc_ transmission.

```C
 ...
    message_size = atoi (argv [1]);
    message_count = atoi (argv [2]);
    int k;
    for (k=0; k<100; k++)
    {
        s = nn_socket (AF_SP, NN_PAIR);
...
```
Max k=100 is quiet enough to reproduce the error but sometimes it happens for less k.

2. For **local_thr/remote_thr** also there is a similar problem. Finally it crashes with the message that _sz=nbytes_ assertion failures.

I guess it is not intended behaviour as for zmq the same works fine. I just wanted to compare performance nnmsg vs zmq to choose the best one and I'm a little bit confused... This happens both for 0.8 and 0.7 versions. OS Ubuntu 14.04.

**Comment by gdamore** [comment] 2016-01-31 17:04
Inproc has known race conditions. It's also not optimally efficient.  I don't recommend it's use at present. For real performance testing you should compare TCP because that's going to be more reflective of real world uses.

**Comment by AlexanderZh** [comment] 2016-01-31 19:48
Thank you for fast reply! Ок, I'll not use inproc. 

But what about **ipc** for example? As I've mentioned above in (2) there is a similar problem. After adding _for loop_ and some _printf_ for diagnostics as follows:
```C
...
k_max = atoi (argv [4]);
    int k;
    for(k=0; k<k_max; k++)
    {
        s = nn_socket (AF_SP, NN_PAIR);
...
    for (i = 0; i != count; i++) {
            nbytes = nn_recv (s, buf, sz, 0);
            if(nbytes != (int)sz)
                printf("got %d instead of %d\n", nbytes, (int)sz );
            assert (nbytes == (int)sz);
        }
...
```
 I get the following output  (last argument 100 is _k_max_ in _for loop_) :
```bash
$./perf/local_thr ipc:///tmp/test123 1024 1000 100
message size: 1024 [B]
message count: 1000
throughput: 228050 [msg/s]
throughput: 1868.186 [Mb/s]
message size: 1024 [B]
message count: 1000
throughput: 202429 [msg/s]
throughput: 1658.298 [Mb/s]
got 0 instead of 1024
lt-local_thr: perf/local_thr.c:75: main: Assertion `nbytes == (int)sz' failed.
Aborted (core dumped)
```
After several loops 0 bytes are received instead of 1024.

As for **tcp** the output is:
```bash
$ ./perf/local_thr tcp://127.0.0.1:5555 1024 1000 100
message size: 1024 [B]
message count: 1000
throughput: 214546 [msg/s]
throughput: 1757.561 [Mb/s]
message size: 1024 [B]
message count: 1000
throughput: 327011 [msg/s]
throughput: 2678.874 [Mb/s]
message size: 1024 [B]
message count: 1000
throughput: 286697 [msg/s]
throughput: 2348.622 [Mb/s]
got 1024 instead of 0
lt-local_thr: perf/local_thr.c:70: main: Assertion `nbytes == 0' failed.
Aborted (core dumped)
```

Sometimes 1024 bytes are received instead of 0 bytes and sometimes vice versa. Does that mean that the order of messages is not preserved between sender and receiver? And is it the intended behaviour?

**Comment by gdamore** [comment] 2016-02-01 04:43
Looks like a bug.  I don't have time to analyze it right now but maybe someone else on the list can help?

**Comment by gdamore** [comment] 2016-05-30 04:46
I think with TCP what may be happening is a failure to linger, causing "written" bytes to get dropped on the floor.  I'm making a change for that to accommodate larger message sizes anyway.  Stay tuned.

**Comment by gdamore** [comment] 2016-05-30 05:12
So, looking at this more fully.  Its not a bug.  You're sending messages, but synchronization of data between senders on different sockets is *not* guaranteed.  In particular, we can have a situation where a socket is lingering (behind the scenes) or retrying, or just delivered via a different TCP stream and hence scheduled differently by the stack, the NIC(s), the routers, etc. 

Only data within a single TCP is guaranteed to be in order.

When you mix different streams together -- e.g. combining several streams and expecting the data to arrive using only a single receiving nanomsg socket -- the system(s) involved a free to intermix data.  What is *guaranteed* is that data from a *single* sending socket will never arrive at the receiving sock out of order.  But it may not be time-ordered against data that was sent from *different* sockets.

Just to make matters worse for you.  I'm not 100% sure the order guarantee applies even then.  Retries, and use of devices (intermediate nanomsg nodes) can wind up breaking the ordering promise.  This is actually a more or less fundamental problem in nanomsg.  Even though nanomsg may use underlying reliable transports for transmission, it does not itself provide reliable in-order delivery.

I'm pretty sure this is a problem for ZMQ too.  That said, I've not actually checked with the protocols.

I'm going to go ahead and close this -- we can't really fix it.

If you need reliable delivery, you really need to use req/rep.

**Closed by gdamore** 2016-05-30 05:12 UTC
