### ISSUE TITLE
nn_send assert when IPv4only option was disabled, and try to connect with IPv4 address

### ISSUE THREAD

**Issue by clearday4** [nanomsg/nanomsg#1007] opened 2018-11-29 12:30 UTC
I'm testing the PUSH/PULL socket using TCP transport.
If IPv4only option was disabled, and try to connect with IPv4 address,
the destination address resolved AF_INET, but local address which the socket would bind resolved as AF_INET6.
so nn_usock_start makes the socket AF_INET.
after that nn_ctcp_start_connecting() try to bind the local IPv6 address, it was failed.
the local address lookup code is not working properly.
nn_iface_any determines the bind address only with ipv4only option.

after that, nanomsg try to reconnect and takes a same routine again.
at that time usock->state is not idle, it is NN_USOCK_STATE_STARTING,
so nn_usock_start is assert.

please consider the following three points

1) nn_iface_any should not determine the address with ipv4only option
2) nn_usock_start should consider connection retry case.
3) if ipv4only option is disabled, make the socket as AF_INET6 forced.

**Comment by clearday4** [comment] 2019-01-31 10:55
We are testing on x86_64 Redhat linux. 
And the nanomsg document mentioned that the NN_IPV4ONLY option can be used for both IPv4 nad IPv6 address.
The url we used for the test is :
"tcp://172.190.0.3:21584"  
We disabled the NN_IPV4ONLY option and try to nn_connect with IPv4 address.

**Comment by gdamore** [comment] 2019-03-08 06:13
Oh, when you disable IPV4_ONLY, you should in theory bind to an IPv4 mapped IPv6 address -- but this is highly dependent on whether the host operating system supports it (which can also be subject to tunables -- for example, it won't do IPv6 if you don't have IPv6 enabled or an IPv6 configured address.)

I'm curious, did you specify a local address as part of the connection URL?  Because nn_ctcp_start_connecting() should not be binding to a local address at all (except on Windows...)

**Comment by clearday4** [comment] 2019-03-11 06:15
The problem is to disable IPV4_ONLY option for using a dual stack,
Assertion occurs at nn_send after IPv4 address connect.
An assertion should not occur at this time.

it is critical issue that may affect the other users, therefore please consider urgent patch.

**Comment by gdamore** [comment] 2021-12-28 23:38
If I'm understanding correctly, it sounds like the local and remote addresses are resolving into different address families?  This seems *highly* undesirable (really a bug in the OS I think.)

I will have a look to see if I can reproduce this.

**Comment by gdamore** [comment] 2024-02-03 22:36
I'm unlikely to work on this.  I'm closing it as aged out.  If its still really important, please reopen.

Note that I think using that if you disable IP4_ONLY you should probably should use an IPv6 address - we expect at that point to get an IPv6 address and use AF_INET6.  If you bind using an IPv4 address, and we then receive IPv6 mapped addresses with AF_INET6, its going to break probably.

Anyway, NNG is a bit more robust (or it should be) in this regard, and that's where my focus is these days.

**Closed by gdamore** 2024-02-03 22:36 UTC
