### ISSUE TITLE
Application Error after close connection on port 5907 

### ISSUE THREAD

**Issue by arencour** [nanomsg/nanomsg#950] opened 2018-02-07 07:17 UTC
Hello! We use nanomsg in our application and have a problem. Some application are imcompatible with nanomsg library (we found LanAgent http://www.lanagent.ru/ and networx). Application Error occurs while our application with nanomsg and these application are working at the same time.
We found simple way to obtain this error using TcpView. 

Select Close Connection for some 5907 connections:
![image](https://user-images.githubusercontent.com/36221766/35903212-38ed6d32-0bef-11e8-88cc-1aa659e8966e.png)

Errors:
![image](https://user-images.githubusercontent.com/36221766/35903228-4d345f44-0bef-11e8-8f05-f0bfe6ab55db.png)

Application Error event:
![image](https://user-images.githubusercontent.com/36221766/35903237-5899128a-0bef-11e8-9dd9-1b7ac63f4817.png)

nanomsg library version 1.1.2, .Net binding https://github.com/mhowlett/NNanomsg

**Comment by arencour** [comment] 2018-02-07 07:41
Another Fault offset
![image](https://user-images.githubusercontent.com/36221766/35904243-7815020a-0bf3-11e8-88d5-c86ea746b7e0.png)

**Comment by gdamore** [comment] 2018-02-07 15:28
So you've disconnected the socket in an unpredicted way.  Some of those sockets may be for the notifications that nanomsg sends itself, and it does not expect to ever have closed.  I could see that causing panics or assertions in the code.

To debug this more fully I'd need to see the actual abort output which should include the assertion message and line number but may require building a debug version of the library.  Can you do that?

**Comment by arencour** [comment] 2018-02-09 05:02
Nanomsg is unmanaged library in our C# application. If you attach debug version of the library I can try to repeat error with it.

**Comment by acviex** [comment] 2018-02-15 12:50
@gdamore You're right. The cause of runtime error in this (Windows) case is 
`wsa_assert (rc != SOCKET_ERROR);` in function `void nn_efd_unsignal (struct nn_efd *self)` in file _efd_win.inc_. This assert makes Windows to finish application, because `rc = 10054` or _**connection reset by peer**_. I think the better solution for this situation is recreate connection instead killing application.

**Comment by gdamore** [comment] 2018-02-15 15:31
yes that would be better. but since the “peer” is the same process the
connection should not ever normally close prematurely.

given that i have moved most of my development effort to nng and that this
error is not something that would ever occur under anything like normal
conditions, i probably will not be investing the effort to fix it.

**Comment by arencour** [comment] 2018-02-15 16:06
Unfortunatly for users it is normal conditions. Their other applications sometimes close these internal connections. We recommend them to remove suspicious application, but sometimes such applications not found in the list of installed programs.

**Comment by gdamore** [comment] 2018-02-15 16:49
It is astounding to me that anyone would expect that closing random tcp
sockets would NOT break applications.

I will think about this. The only reason we use this socket is because
windows only supports TCP/IP sockets with the select() function.

**Comment by gdamore** [comment] 2018-02-15 18:40
Unfortunately, while I could fix the underlying panic, the fact is that closing the underlying TCP connection is going to cause bad breakage.  We rely on the file descriptor for notification, and closing and reopening will *change* the file descriptors used, causing the application to fail in other ways.

It might be possible to reuse one side (the connect side) by issuing connect again, but I'm not sure if Windows allows socket descriptor reuse in this way.  The server side can't be done, as accept() always returns a *new* socket descriptor.

You need to instruct your users to cease closing sockets that they do not recognize in this way.  It is unreasonable to expect all applications to survive random attempts to rip out connections that they believe are fully under their control.  (It would also be unreasonable to expect them to survive deletion of databases they have exclusively opened, removal of their named pipes, or unmapping of shared memory regions.  It would also be unreasonable for them to expect an application to survive loss of power.  Yet an administrator can do any of these things.)

I would be willing to contemplate ways to cause a specific port number to be used (right now an ephemeral port is used, and acquired exclusively -- this should be a random port number assigned by the system) or possibly to convert the code to set up an IPv6 socket instead of an IPv4 socket (although I'd want to confirm that Windows systems we support always have the ability to create an IPv6 loopback socket) -- but those are hacks to just "avoid" whatever crazy stunts your users are pulling with aborting sockets that they have no business messing with.

In the meantime, no, I won't be fixing this "bug" -- because it's not a bug; its a failure of the application to survive unreasonable administrator actions, and the solution is to stop doing those unreasonable actions.  (If its an application that is doing this without the user's consent, then the application that is doing it is buggy, and should be fixed.)

**Closed by gdamore** 2018-02-15 18:40 UTC
