### ISSUE TITLE
Device is not working properly RESPONDENT/SURVEYOR

### ISSUE THREAD

**Issue by keshav105** [nanomsg/nanomsg#544] opened 2015-11-22 12:48 UTC
ISSUE: We have written piece of code to communicate client and server with the help of proxy. when we are trying to have TCP connection between proxy and server then we are facing following few issues.

Note here following sockets are assigned to server , proxy and client.

Server → sock0
proxy → sock1, sock2
client → sock3

         connect           bind                                      connect                        bind
sock3 --------------> <---------------sock1      sock2-------------------> <--------------------sock0
client                                                   Proxy                                                                Server

1) when sending msg of size 12 from server its hanging at client side mean not able to get any msg at client side.
For example. Please check OUTPUT: when buff size is 12 and connection is TCP.

2) when sending msg of size 12 from server its failing when trying to receive at server side..
For example. Please check OUTPUT: when buff size is 12 and connection is INPROC.

// Standalone code for nanomsg.

class NNHTest : public ::testing::Test
{
public:
nn_helper_t proxy_st ;
};

struct info_my_param_t
{
int sock1;
int sock2;
};

static void * loop_device( void* args )
{
int rc;
struct info_my_param_t * imp = (struct info_my_param_t *) args ;

rc = nn_device ( imp->sock1, imp->sock2 );
printf("value of rc = %d\n", rc);

return NULL;
}

TEST_F(NNHTest, ProxyBroadcastReqResp )
{
    int rc ,nnbd, con;

//step 1. server init

    int sock0 = nn_socket ( AF_SP , NN_SURVEYOR );
    printf("value of sock0 = %d\n", sock0);

    nnbd = nn_bind ( sock0 , "tcp://127.0.0.1:6799" );
    //nnbd = nn_bind ( sock0 , "inproc://SERVER" );
    printf("value of nnbd = %d\n", nnbd);

//step 2. proxy init

    int sock1 = nn_socket ( AF_SP_RAW , NN_SURVEYOR );
    printf("value of sock1 = %d\n", sock1);

    nnbd = nn_bind ( sock1 , "tcp://127.0.0.1:6699" );
    //nnbd = nn_bind ( sock1 , "inproc://CLIENT" );
    printf("value of nnbd = %d\n", nnbd);

    int sock2 = nn_socket ( AF_SP_RAW , NN_RESPONDENT );
    printf("value of sock2 = %d\n", sock2);

    con = nn_connect ( sock2 , "tcp://127.0.0.1:6799" );
    //con = nn_connect ( sock2 , "inproc://SERVER" );
    printf("value of con = %d\n", con);

//step 3. proxy loop start

    struct info_my_param_t imp ;
    imp.sock1 = sock1 ;
    imp.sock2 = sock2 ;
    struct info_my_param_t *ptr = (struct info_my_param_t *)memdup( (char*)&imp, sizeof(struct info_my_param_t) )  ;

    rc = pthread_create( &proxy_st.threadid, NULL, loop_device, ptr  );
    printf("value of pthread_create rc = %d\n", rc);

//step 4. client init

     int sock3 = nn_socket ( AF_SP , NN_RESPONDENT );
     printf("value of sock3 = %d\n", sock3);

     con = nn_connect ( sock3 , "tcp://127.0.0.1:6699" );
     //con = nn_connect ( sock3 , "inproc://CLIENT" );
     printf("value of con = %d\n", con);

//step 5. server sending data

     char buf[] = "TEST_STRING";

     rc = nn_send ( sock0, buf, sizeof( buf ), 1 );
     printf("string send by server nn_send rc =%d, buffer = %s\n", rc, buf);

//step 6. client recv data
     char buffer[256];
     memset(&buffer, 0x00, sizeof(buffer));
     sleep(1);
     rc = nn_recv ( sock3, buffer, sizeof(buffer) , 0 );
     sleep(1);
     printf("string receive by client nn_recv rc =%d, buffer = %s\n", rc, buffer);

//step 7. client send back data
    rc = nn_send ( sock3, buf, sizeof( buf ), 1 );
    printf("string send by client nn_send rc =%d, buffer = %s\n", rc, buf);

//step 8. server received data back
     memset(&buffer, 0x00, sizeof(buffer));
     rc = nn_recv ( sock0, buffer, sizeof(buffer) , 0 );
     sleep(1);
     printf("string received by server nn_recv rc =%d, buffer = %s\n", rc, buffer);

}

OUTPUT: when buff size is 12 and connection is TCP.

keshav@keshav-Latitude-E6540:~/clone/BD/Test/Shared/Core$ ./ubuntuRelease64/test-static --gtest_filter=NNHTest.ProxyBroadcastReqResp
Note: Google Test filter = NNHTest.ProxyBroadcastReqResp
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from NNHTest
[ RUN      ] NNHTest.ProxyBroadcastReqResp
value of sock0 = 0
value of nnbd = 1
value of sock1 = 1
value of nnbd = 1
value of sock2 = 2
value of con = 1
value of pthread_create rc = 0
value of sock3 = 3
value of con = 1
string send by server nn_send rc =12, buffer = TEST_STRING
Note: Its hanging here.

OUTPUT: when buff size is 12 and connection is INPROC

keshav@keshav-Latitude-E6540:~/clone/BD/Test/Shared/Core$ ./ubuntuRelease64/test-static --gtest_filter=NNHTest.ProxyBroadcastReqResp
Note: Google Test filter = NNHTest.ProxyBroadcastReqResp
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from NNHTest
[ RUN      ] NNHTest.ProxyBroadcastReqResp
value of sock0 = 0
value of nnbd = 1
value of sock1 = 1
value of nnbd = 1
value of sock2 = 2
value of con = 1
value of pthread_create rc = 0
value of sock3 = 3
value of con = 1
string send by server nn_send rc =12, buffer = TEST_STRING
string receive by client nn_recv rc =12, buffer = TEST_STRING
string send by client nn_send rc =12, buffer = TEST_STRING
string received by server nn_recv rc =-1, buffer = 
Segmentation fault (core dumped)
keshav@keshav-Latitude-E6540:~/clone/BD/Test/Shared/Core$

**Comment by gdamore** [comment] 2015-11-22 15:26
Please don't use inproc. Due to another bug it fails to transport message headers.

**Comment by keshav105** [comment] 2015-11-23 06:21
But its not working in the case of TCP also. As already mentioned its hanging.

**Comment by gdamore** [comment] 2015-11-23 15:43
Ok I will write a test case and see if I can debug.

**Comment by gdamore** [comment] 2015-11-23 16:34
Well, my test, which are derived from tests/device5.c, work fine.  I can pass both surveys and replies across multiple devices.

What version of nanomsg are you using?

I'll go ahead and post device6.c up so you can try it yourself.

**Comment by gdamore** [comment] 2015-11-23 16:35
Note especially that you *must* use either the version head from git, or v0.8 (or later, though 0.8 is the latest).  Earlier versions of nanomsg (including 0.7) probably won't work at all.

**Comment by gdamore** [comment] 2015-11-23 16:38
So the change I posted for #547 add this test.  Please have a try yourself.

**Comment by gdamore** [comment] 2015-11-23 16:39
And I believe that this is the same as problem #521 -- and probably fixed by the same commit:

commit e9343578ce0dc4e3b42adb141ba10ee0bd1f5b4c
Author: Garrett D'Amore <garrett@damore.org>
Date:   Mon Nov 16 15:56:08 2015 -0800

    fixes #521 Multiple Devices are not working properly REQ/REP

As I said, I cannot reproduce your results on the latest code base.

**Comment by keshav105** [comment] 2015-11-23 17:03
Hiii .. I am using the version 0.8 only... As you told i will try it and let you know.. thanks .

**Comment by gdamore** [comment] 2015-11-23 19:35
Well, this is interesting.  I've seen one hang on Linux here, but other times it just works.  And it fails consistently on Windows.  I don't understand what is going on here, but I don't think its header file misparse.  Something else is happening.

I'd appreciate help from someone more familiar with Windows in debugging this.  I have a theory that we have some kind of limitations on port #'s or number of active TCP sessions in AppVeyor.  To be honest, TCP testing on Windows seems really really fragile, where one program even causes other programs to fail badly in ways that I don't understand.

**Comment by keshav105** [comment] 2015-11-23 19:55
So you mean to say, you are able to reproduce this issue in Linux ??

**Comment by gdamore** [comment] 2015-11-23 19:58
I’m not sure I can reliably repro it on Linux yet.

**Comment by gdamore** [comment] 2015-11-23 19:58
I saw one hang in device6 which may have been this, or may have been a port
conflict (TCP) or something else.

**Comment by gdamore** [comment] 2015-11-23 19:58
It does not reproduce at all on MacOS X.

**Comment by gdamore** [comment] 2015-11-23 20:00
TBH, I think the epoll implementation of efd on Linux is somewhat buggy.  I wish I could abandon that crap and just use ordinary poll() instead of these 'newfangled' interfaces that I think cause more problems than they solve.

**Comment by keshav105** [comment] 2015-11-23 20:06
Okay.. the test case what i have wrote it was hanging all times i tried. i will try it once more and update you.

**Comment by gdamore** [comment] 2015-11-23 21:49
It definitely hangs sometimes -- please let me know if device6.c (in the latest repo as of this morning) hangs for you reproducibly.  Its a very small test case, so knowing it fails will tell me something.

**Comment by gdamore** [comment] 2015-11-23 21:59
Ok, I've done some more testing, and I could occasionally reproduce this on Linux on my VM.  One test in about 5 to 10.  Increasing the startup delay after nn_connect() to 200 msec solves it though.  The issue is TCP slow start.

We don't see this with REQ/REP, because we queue those requests for delivery as it is guaranteed delivery, whereas for SURVEYOR, if there is no respondent, the message is dropped on the floor.

Increasing the delay in device6 to 200 msec solves it.

You probably need to add a delay as well.  You can't connect and immediately start sending; you have to wait for TCP (or whatever) to establish the connection before you send messages.  This is a well understood property of "TCP slow start".

I'm going to change the test to add the 200 msec startup, and close this bug with that test result.

**Closed** 2015-11-23 22:01 UTC

**Comment by gdamore** [comment] 2015-11-23 22:11
Well, crapola.  It *still* hangs on Windows.  But works 100% of the time on Linux now.  I think this may be another case of too many TCP connections on Windows == fail.  Or possibly, Windows needs longer (more than 200 msec?!?!) to establish a TCP connection.

**Comment by gdamore** [comment] 2015-11-23 22:37
YEP.  200 Msec isn't enough.  Waiting a full *second* works fine.  Yikes, that's just very very sad.  At least for people stuck on Windows.

**Comment by wirebirdlabs** [comment] 2015-11-23 23:11
> YEP. 200 Msec isn't enough. Waiting a full second works fine. Yikes, that's just very very sad. At least for people stuck on Windows

Is this *really* the root cause? Surely not. Does increasing time to 1000msec (1sec) fix the issue *every* time reliably? If so, you might be right here, but I suspect in that case time is just masking a more precise root cause.

**Comment by gdamore** [comment] 2015-11-24 00:36
Well if it didn’t fix the issue, it dropped the occurrence rate from ~1/5
of the time to something less than 1%.  I ran several hundred invocations
with no reproducibility.

And since this isn’t in an otherwise concurrent part of the code, there is
no particular reason for me to believe that it is explainable for any other
reason.  And yet, the TCP slow start explanation can be used to address
both this failure mode, and the reason why we didn’t see it with REQ/REP
(because that mode includes reliable delivery features in the pattern,
whereas SURVEYOR just drops the messages.)

On Mon, Nov 23, 2015 at 3:11 PM, Wirebird Labs LLC <notifications@github.com
