### ISSUE TITLE
Static Lib compiled with VS2012 on Windows is missing symbols.

### ISSUE THREAD

**Issue by mascojames** [nanomsg/nanomsg#764] opened 2016-06-10 17:54 UTC
After compiling the nanomsg static library using Visual Studio 2012, it appears symbols are missing from the nanomsg.lib file that is generated.

When linking against this library I get missing symbols:
my_class.lib(my_class.obj) : error LNK2001: unresolved external symbol __imp_nn_errno
my_class.lib(my_class.obj) : error LNK2001: unresolved external symbol __imp_nn_strerror
my_class.lib(my_class.obj) : error LNK2001: unresolved external symbol __imp_nn_freemsg
my_class.lib(my_class.obj) : error LNK2001: unresolved external symbol __imp_nn_socket
my_class.lib(my_class.obj) : error LNK2001: unresolved external symbol __imp_nn_close
my_class.lib(my_class.obj) : error LNK2001: unresolved external symbol __imp_nn_setsockopt
my_class.lib(my_class.obj) : error LNK2001: unresolved external symbol __imp_nn_bind
my_class.lib(my_class.obj) : error LNK2001: unresolved external symbol __imp_nn_connect
my_class.lib(my_class.obj) : error LNK2001: unresolved external symbol __imp_nn_shutdown
my_class.lib(my_class.obj) : error LNK2001: unresolved external symbol __imp_nn_send
my_class.lib(my_class.obj) : error LNK2001: unresolved external symbol __imp_nn_recv

After checking the lib using dumpbin, these symbols are not found and all their nn_* counterparts are defined as externals.

CMake command (in a build directory) used to generate this lib:
cmake -G "Visual Studio 11 Win64" -DNN_STATIC_LIB=ON ..

Creating the static lib in a similar way on a CentOS 7 box did not have any issues and linked with the same code base I am seeing errors with on Windows.

 I've attached the generated static lib for your review.
[nanomsg.lib.zip](https://github.com/nanomsg/nanomsg/files/309486/nanomsg.lib.zip)

**Comment by Snaipe** [comment] 2016-06-10 19:11
Oh. It seems that Visual Studio is trying to link against the dynamic link version of the library -- mostly because `NN_STATIC_LIB` isn't defined in your user build, which in turn prepend `__declspec(dllimport)` to all functions.

@gdamore, what's your stance on this? Should the user always define `NN_STATIC_LIB` in their user build with a static nanomsg, or should nanomsg install a `config.h` header that provides that definition conditionally?

**Comment by gdamore** [comment] 2016-06-10 19:33
Hmm.. I will have to investigate this further.

**Comment by gdamore** [comment] 2016-06-10 23:55
I think static builds are non default and the user should put this in their environment.  Our header files are not generated at present.

**Comment by gdamore** [comment] 2016-06-13 18:51
Sheesh I hate Windows DLL crap. 

So if you're not using the default built, then its on the user's shoulders to make it work.  I'm closing as not a bug.

**Closed by gdamore** 2016-06-13 18:51 UTC

**Comment by sailfish009** [comment] 2016-07-29 05:55
Hi, i had same problem, solved it by follow.

////////////////////// sample.cpp +25

#include "../include/nn.h"
#include "../include/pair.h"
#include "../include/utils/attr.h"
#include "../include/utils/err.h"
#include "../include/utils/thread.h"
#include <stddef.h>
#include <assert.h>
#include <stdlib.h>
#include <string.h>

#pragma comment(lib,"nanomsg.lib")
#pragma comment(lib,"Ws2_32.lib")
#pragma comment(lib,"wsock32.lib")

//////////////////////nn.h +366
#if 1
//static
int nn_socket(int domain, int protocol);
int nn_close(int s);
int nn_setsockopt(int s, int level, int option, const void *optval,
  size_t optvallen);
int nn_getsockopt(int s, int level, int option, void *optval,
  size_t *optvallen);
int nn_bind(int s, const char *addr);
int nn_connect(int s, const char *addr);
int nn_shutdown(int s, int how);
int nn_send(int s, const void *buf, size_t len, int flags);
int nn_recv(int s, void *buf, size_t len, int flags);
int nn_sendmsg(int s, const struct nn_msghdr *msghdr, int flags);
int nn_recvmsg(int s, struct nn_msghdr *msghdr, int flags);

typedef void (nn_thread_routine)(void*);
void nn_thread_init(struct nn_thread *self, nn_thread_routine *routine, void *arg);
void nn_thread_term(struct nn_thread *self);

struct nn_stopwatch {
  uint64_t start;
};

void nn_stopwatch_init(struct nn_stopwatch *self);
uint64_t nn_stopwatch_term(struct nn_stopwatch *self);

#else
// shared

NN_EXPORT int nn_socket (int domain, int protocol);
NN_EXPORT int nn_close (int s);
NN_EXPORT int nn_setsockopt (int s, int level, int option, const void *optval,
    size_t optvallen);
NN_EXPORT int nn_getsockopt (int s, int level, int option, void *optval,
    size_t *optvallen);
NN_EXPORT int nn_bind (int s, const char *addr);
NN_EXPORT int nn_connect (int s, const char *addr);
NN_EXPORT int nn_shutdown (int s, int how);
NN_EXPORT int nn_send (int s, const void *buf, size_t len, int flags);
NN_EXPORT int nn_recv (int s, void *buf, size_t len, int flags);
NN_EXPORT int nn_sendmsg (int s, const struct nn_msghdr *msghdr, int flags);
NN_EXPORT int nn_recvmsg (int s, struct nn_msghdr *msghdr, int flags);

#endif

//////////////////////global.c +986
void nn_stopwatch_init(struct nn_stopwatch *self)
{
  LARGE_INTEGER time;

  QueryPerformanceCounter(&time);
  self->start = (uint64_t)(time.QuadPart);
}

uint64_t nn_stopwatch_term(struct nn_stopwatch *self)
{
  LARGE_INTEGER tps;
  LARGE_INTEGER time;

  QueryPerformanceFrequency(&tps);
  QueryPerformanceCounter(&time);
  return (uint64_t)((time.QuadPart - self->start) * 1000000 / tps.QuadPart);
}

**Comment by sailfish009** [comment] 2016-08-23 08:19
today, i rebuilt nanomsg with follow modification.

#include "utils/thread.h"
//typedef void (nn_thread_routine)(void*);
//void nn_thread_init(struct nn_thread *self, nn_thread_routine *routine, void *arg);
//void nn_thread_term(struct nn_thread *self);

**Comment by flyingdove** [comment] 2017-04-03 11:11
just add NN_STATIC_LIB in preprocessor flags in your project
