### ISSUE TITLE
Pub/sub appears to be silently dropping messages when sending in bursts

### ISSUE THREAD

**Issue by dasques** [nanomsg/nanomsg#390] opened 2015-03-18 18:00 UTC
My publisher sends a large number of messages (e.g. 5000) in a single burst, and occasionally some of the messages are being missed by the subscribers. 

I have boiled down the issue to two simple programs, a publisher and a subscriber, described in the below pseudo-code. (I will post the actual code later below.)

Publisher:
```c
seqNumber = 0;
while (true)
{
    do 5000 times
    {
        publish a message containing seqNumber.
        ++seqNumber;
    }
    Sleep 1 second.
}
```

Subscriber:
```c
while (true)
{
    Receive message.
    Assert message seqNumber is 1 higher than last.
}
```

When I run the publisher, and 3 subscribers, very quickly (within seconds) I see one of the subscribers complain of missed sequence numbers.

Some caveats:
1. My test machine was a linux VM, with 2 cpus, 4GB ram.
2. I can't see the issue on my physical linux box.
(However, if you run remove the "Sleep 1 second" above and run it for a long time, it still exhibits the same issue, but I'm thinking this is not necessarily as serious, given we are pushing the system to the limit.)
3. I tried upping NN_SNDBUF and NN_RCVBUF to 32MB (from 128k), but this did not help.
4. While I'm sending the burst, if every 10 messages, I put in sleep of 1 *micro second*, the problem goes away.
5. When I run 3 subscribers, it's usually only one that fails after a while.
6. When I use nanocat to subscribe and pipe the messages to a file, I see the same issue, messages being missed. It's to eliminate nanocat that I made my own simple subscriber.
7. Version nanomsg-0.5-beta.
8. The message size is 250 bytes, including the sequence number.

So my questions are:
1. Given the code shown below, is there anything I'm doing anything wrong?
2. Shouldn't something e.g. nn_send, return an error if for whatever reason it can't send all the messages to all the subscribers?

Publisher:
```c
#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "nn.h"
#include "pubsub.h"

char* tmplt = 
  "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij"
  "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij"
  "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij"
  "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij"
  "abcdefghijabcdefghijabcdefghijabcdefgh %010d"; // 249 bytes.

int counter = 0;

int server(const char *url, int msgsPerBurst)
{
  int sock = nn_socket(AF_SP, NN_PUB);
  assert(sock >= 0);

  // Set NN_SNDBUF size. Note: this is not required to reproduce the issue.
  int setBufSize = 32 * 1024 * 1024;
  assert(nn_setsockopt(sock, NN_SOL_SOCKET, NN_SNDBUF, &setBufSize, sizeof(setBufSize)) == 0);

  assert(nn_bind(sock, url) >= 0);
  while (1)
  {
    int ix = 0;
    for (ix = 0; ix < msgsPerBurst; ++ix)
    {
      char* buf = nn_allocmsg(250, 0);
      snprintf(buf, 250, tmplt, counter);
      int szBuf = 250;
      int bytes = nn_send(sock, &buf, NN_MSG, 0);

      assert(bytes == szBuf);

      // Uncommenting this makes it a lot better!
      //if (counter % 10 == 0)
      //  usleep(1); // Note: 1 microsecond.

      ++counter;
    }

    printf("Published %d\n", counter);
    sleep(1); // Note: 1 full second.
  }
  return nn_shutdown(sock, 0);
}


int main(const int argc, const char **argv)
{
  if (argc >= 3)
    return server(argv[1], atoi(argv[2]));
  else
  {
    fprintf (stderr, "Usage: burst_publisher <URL> <msgsPerBurst>\n");
    return 1;
  }
}
```

Subscriber:
```c
#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "nn.h"
#include "pubsub.h"

int lastSeqNum = -1;
int count = 0;

void process(char* rec, int bytes)
{
	char* space = strstr(rec, " ");
	int seqNum = atoi(space + 1);

	if (lastSeqNum == -1)
		printf("Saw first msg, seqNum: %d\n", seqNum);
	else if (seqNum != lastSeqNum + 1)
	{
		printf("Oops! seqNum %d following %d, exiting after receiving %d messages.\n", seqNum, lastSeqNum, count);
		exit(1);
	}

	lastSeqNum = seqNum;
	++count;
}

int subscribe(const char *url)
{
  int sock = nn_socket(AF_SP, NN_SUB);
  assert(sock >= 0);

  // Set NN_RCVBUF size. Note: this is not required to reproduce the issue.
  int setBufSize = 32 * 1024 * 1024;
  assert(nn_setsockopt(sock, NN_SOL_SOCKET, NN_RCVBUF, &setBufSize, sizeof(setBufSize)) == 0);

  assert(nn_setsockopt(sock, NN_SUB, NN_SUB_SUBSCRIBE, "", 0) >= 0);
  assert(nn_connect(sock, url) >= 0);
  while (1)
  {
    char *buf = NULL;
    int bytes = nn_recv(sock, &buf, NN_MSG, 0);
    assert(bytes >= 0);

    if (bytes > 0)
 		process(buf, bytes);
      
    nn_freemsg(buf);
  }
  return nn_shutdown(sock, 0);
}

int main(const int argc, const char **argv)
{
  if (argc >= 2)
    return subscribe(argv[1]);
  else
  {
    fprintf(stderr, "Usage: burst_subscriber <URL>\n");
    return 1;
  }
}
````

Here's a typical output from a subscriber:
```c
Saw first msg, seqNum: 20000
Oops! seqNum 47858 following 47830, exiting after receiving 27831 messages.
```

**Comment by vseryakov** [comment] 2015-04-27 18:40
can it be that messages arrive in different order?

**Comment by gdamore** [comment] 2015-05-02 21:29
pub & sub are best effort.  In particular, if you submit messages faster than your TCP stack can process them, they get dropped on the floor -- there is no pushback.

The drop may even occur not in the sending side but on the receiver side!  (The sender will never know that the message hasn't been received.)  Additionally, its possible that the sending be done asynchronous (mangos does this), so that the sender returns even *before* all the messages are delivered to the underlying stack (or dropped if the underlying stack cannot accept them.)

In fact the only way to "fix" this is to use a different paradigm.  If you want acknowledged receipt, you need to use a protocol like REQ/REP, or you need to use an application layer protocol that handles this.  Note that these things are really really poorly suited for multicast/broadcast communication, so you probably have a mismatch in your model if you're trying to achieve this with pub/sub.

Note that VMware or other systems introduce additional stack latency, and are also therefore more likely to result in dropped messages.  (The time it takes to context switch into the VM, and then for the VM to bring in the application to receive the message plays a double role.)

Btw, these problems are also a good example of why pub/sub should not be used to stream huge amounts of data, particularly if you want to avoid data loss.  It works well for lighter loads with modest amounts of gap between packets (as you noted, even 10 us can help), but pounding as hard as you can will almost certainly cause lost messages.

I'm closing this as the problem is not with nanomsg, but rather with your usage and understanding the limitations of the design.

**Closed by gdamore** 2015-05-02 21:29 UTC
