### ISSUE TITLE
Support binding to a random free port 

### ISSUE THREAD

**Issue by amosbird** [nanomsg/nanomsg#382] opened 2015-03-10 13:49 UTC
I know that binding to port 0 may reopen a non-nanomsg socket and bad things happen. But in some distributed computing framework, the ability to dynamicly choose available ports is vital.

**Comment by reqshark** [comment] 2015-03-10 14:00
Isn't that like binding to a random namespace for inproc or ipc? 

Im not seeing how that would help when its corresponding tcp socket must meet with a precise port number in its connection string.

**Comment by amosbird** [comment] 2015-03-10 14:19
@reqshark This is what I suppose to do: There will be a metadata manager that answers queries of which connection strings to be used. After a successful binding, a registration to the manager should be done in order to make socket online.

**Comment by reqshark** [comment] 2015-03-10 14:40
@amosbird, that scheme sounds overly procedural and specific for such accommodations by library.

but that's just my opinion, and you may be onto something after-all.

One way this would make sense to me is if the random bind function somehow returned which port was bound, or perhaps in the alternative, if a later call to `getsockopt()` with level `NN_TCP` returned additional information about the socket's connection string.

**Comment by diffuse** [comment] 2015-03-10 15:36
I don't think it is necessarily the best idea to implement application
specific features in nanomsg....

You can just do somethign similiar to this in your software:

retry_bind:
    port = generate_random_port();
    service_string = "tcp://127.0.0.1:%d" % port;

    rc = nn_bind(sock, service_string);

    if (rc < 0)
    {
         if (rc == INUSE)
             goto retry_bind;
     }

....

**Comment by gdamore** [comment] 2015-03-10 22:44
Actually, binding to a random port is better, because its atomic.  What I mean is, you bind, and you know you got the port.  If you try to generate one randomly (and do the work to ensure it isn't already in use), and then rebind later, the port might be unavailable as another application can take it between the randomization and the binding.  You can do some things to make this window small, but its definitely the case that using a randomized port can be better because of atomicity. 

It would be useful also to allow for applications to randomly bind to a *reserved* port (traditionally a port number less than 1000 -- or maybe 1024 -- I don't remember right now). 

So, I support this RFE in principle.

**Comment by reqshark** [comment] 2015-03-18 02:58
> port might be unavailable as *another application* can take it between randomization and binding...

randomized port unavailability scenerios requiring atomicity seem plausible to me.

in light of the snippet above, however, I'm going to side with @diffuse on this one

**Comment by wirebirdlabs** [comment] 2015-03-18 03:18
> "Actually, binding to a random port is better, because its atomic."

This would be the only acceptable implementation. Except...

The reason nanomsg does not support this is by design. Just a few sources for rationale:
* https://github.com/nanomsg/nanomsg/issues/217#issuecomment-38249958
* https://www.freelists.org/post/nanomsg/Bind-random-port,2
* https://github.com/nanomsg/nanomsg/issues/67#issuecomment-18535567

I used to agree more with the desire to bind to ephemeral ports, but after 1yr or so of usage, appreciate the mentality of moving away from this. Utilizing the full URI of the resource (with WebSocket or TCPmux) is a game-changer.

I would tend to recommend application architecture that follows the spirit of Martin's original intent, and I would tend to recommend closing this case as a "Won't Implement". Not 100% yet, but it's sure compelling, and has so far made our applications better!

**Comment by gdamore** [comment] 2015-03-18 05:22
Martin has declared, that the real problem is the small port space. That's true.  (There is another problem that TCPmux and websocket solve, and that is dealing with firewall and configuration rules -- having too many ports makes it hard for admins to cope, but that's actually not solved by ephemeral ports -- indeed ephemeral ports make it worse.)  The other part of the port problem space is that it forces administrators to choose a port to run on.  When you have a microservices architecture, this gets onerous, as you can have dozens or more services -- managing the port allocations for each is a pain.

TCPmux  is an interesting solution to the problem, and with broader adoption could be a fix.  But the hackery needed to make it work is non-portable, and frankly I don't see it getting much adoption.

WebSocket is an *extremely* compelling solution.  Except.  Libnanomsg's implementation is woefully deficient.  While it speaks the websocket protocol in a manner sufficient to act as a client, the server side does not support multiplexing on port, and does not inspect the URI ever.  The libnanomsg websocket implementation is nothing better, IMO, than a toy, compared to what *could* be achieved.

mangos is an alternate implementation, and supports fully multiplexing multiple SP sockets (as well as non SP content, such as static HTML or Javascript content, or other application layer protocols) on a single TCP port, using the URI to direct traffic to the proper handler.  This is possible because mangos uses the Go full HTTP framework.  Getting libnanomsg to do the same thing would require solving a bunch of non-portable problems, or introducing a full HTTP server framework into libnanomsg.  That doesn't seem very realistic.

What I can say is that I've found the ability to bind a listener to a random socket very useful -- we use an RPC bind like mechanism, where the central dispatcher acts as a surveyor, and microservers run respondents that indicate the port where they are providing REQ/REP services.  (As well as other details about the services they are offering.)  This makes running these servers a zero-administration effort.  It would be much harder to do this if we can't have random port binding.

**Comment by gdamore** [comment] 2015-03-18 05:27
Certainly, you can hack this in software as diffuse indicates.  But libnanomsg's bind may not be atomic either -- so you may not know about the bind failure.  The problem is the disconnect between libnanomsg's bind and the actual BSD socket bind.  If you actually know that the bind failed, so you can try again, then the approach works well.  But libnanomsg tends to hide these kinds of problems from applications.  (actually, this makes supporting a random port harder too -- because you do not know if the port is actually bound yet... but that's another problem.)

**Comment by reqshark** [comment] 2015-03-18 05:39
> introducing a full HTTP server framework into libnanomsg. That doesn't seem very realistic

libzmq calls that a [`stream` socket type](https://github.com/zeromq/libzmq/blob/d4c5dc9b1d21686d50d687a584133e4543908069/doc/zmq_socket.txt#L336)

**Comment by gdamore** [comment] 2015-03-18 05:43
There are other approaches that could be used.  It's unclear to me how easily they can be done given the current libnanomsg architecture.  Mangos gets this trivially but it has a much more flexible architecture and far simpler design constraints.

**Comment by gdamore** [comment] 2015-10-26 00:37
There's almost no chance I'm going to do this for libnanomsg prior to 1.0.  Something to consider for a major refactor though.  I'm closing this for now.

**Closed by gdamore** 2015-10-26 00:37 UTC
