### ISSUE TITLE
NN_DONTWAIT flag in nn_send has no effect

### ISSUE THREAD

**Issue by anshumang** [nanomsg/nanomsg#470] opened 2015-10-02 16:23 UTC
The time spent in nn_send that I measured with and without this flag is almost the same. It takes around 25ms for a message of size 7 bytes. The socket is configured as NN_PUSH (and the one on the other side as NN_PULL).

**Comment by wirebirdlabs** [comment] 2015-10-12 17:03
Can you show a test case? I think the behavior you're seeing here may actually be describable and expected.

**Comment by gdamore** [comment] 2015-10-12 17:30
This may be depend on the transport.  Reading the code, what the socket does do is try to find an available socket (one with no backpressure), and run the send on it.  What it does not do is actually use operating system level non-blocking I/O. 

This means that NN_DONTWAIT can actually get stuck for a while, if the operating system stalls the I/O.  The *next* send won't block, but that first one will.

This is an artifact of how nanomsg is handling the send.  Its not running this off on another thread or anything like that.

The intention in this design is to ensure that you don't get blocked due to excessive backpressure, not to ensure a very quick return back to the application.

There is an argument that documentation could be made clearer here.  There is also an argument that could be made that a quick return back to the application, and running the send on a separate thread or using asynchronous I/O would be nice.  The former is a relatively easy thing to do.  The latter needs a redesign (we really need/want threading!)

**Comment by anshumang** [comment] 2015-10-12 17:46
@wirebirdlabs  I will try to post my testcase....it's kind of messy to extract from the application. @gdamore It creates a problem to use a separate thread if there's a need to do a bunch of sends inside a short span of time. If this is of any help, I tried with zeromq and came across the same issue !

**Comment by gdamore** [comment] 2015-10-12 19:04
Not surprising... both 0mq and nanomsg have the same initial author. :-)

The real problem here is that we need to redesign the library to better
support fully asynchronous sending/IO.  Its been on my project list for a
while now.

On Mon, Oct 12, 2015 at 10:46 AM, Anshuman Goswami <notifications@github.com

**Comment by wirebirdlabs** [comment] 2015-11-24 02:12
My suspicion is that this case can be closed as "not a bug".

@anshumang -- my hunch is that you invoked `nn_send()` immediately after `nn_bind()`, and measured the amount of time it took to enter and return from `nn_send()` as 25msec.

nanomsg behaves a bit differently than you might expect during both `nn_bind()` and `nn_connect()` -- both functions are effectively asynchronous.

Meaning, by the time `nn_bind()` has returned with no error, *binding has not yet actually occured*.

Meaning, the first `nn_send()` (or `nn_recv()`), if invoked immediately after either `nn_bind()` (or `nn_connect()`), is likely to incur the entire time penalty of the actual binding/connection process.

The first `nn_send()` might take 25msec, but the next one (after bind is successfully established) will be microseconds.

Hope this helps!

**Comment by gdamore** [comment] 2015-11-24 05:17
@wirebirdlabs you're partly correct, but that's really because we don't do the send asynchronously really.  We can wind up blocking here, when we ought not to.  What happens is that we wind up trying to send on the same thread that issued the nn_send().

That's both a good thing, and a bad thing.

Its a good thing because most of the time it means we notice errors from the transport.  But not always.

Its a bad thing because it defeats the fire-and-forget design that makes nanomsg attractive for high message rate applications.

What really needs to be done here is work to ensure that nn_send() can't get stuck forever, that it acts asynchronously *EXCEPT* in cases where backpressure is present and NN_MSG_DONTWAIT isn't specified.

Probably fixing this is too much effort at this point -- the real fix is to redesign this to be sanely MT and run from synchronous threads instead of the FSM and non-blocking I/O that we currently use.

**Comment by gdamore** [comment] 2015-11-24 05:19
Upshot of this, is that I'm not yet convinced its right to just close this bug.  The 25 msec delay is just too painful, and taking such a stall when e.g. another connection is coming up or going away, isn't really a great thing.

**Comment by wirebirdlabs** [comment] 2015-11-24 05:34
What you say is not incorrect ... but the "no-block guarantee" of `NN_DONTWAIT`might be better communicated as "won't try twice" versus the not-as-correct-assumption "requires a vanishingly small amount of quasi-deterministic time".

**Comment by gdamore** [comment] 2016-04-27 00:32
I'm looking at a possible redesign of the queuing here, which would disconnect the application.  In that case NN_MSG_DONTWAIT would simply mean to try a non-blocking send, and fail otherwise.  The actual send would be run asynchronously by another thread.  This would represent a one message deep queue, but I think this brings enough benefits to be worth doing for reasons other than this particular issue.

**Comment by gdamore** [comment] 2017-01-21 01:11
libnng has actually taken that approach, more or less.  The don't wait flag means don't wait for buffer space to be available -- it once the message is buffered, the sender thread returns back to the caller; the message won't necessarily have been placed on the wire yet.

**Comment by gdamore** [comment] 2017-10-13 06:43
There is some confusion above.

The actual underlying I/O is non-blocking.... *BUT*, nanomsg never buffers anything itself.  As a result, if NN_DONTWAIT is specified, and we can't "send" the entire message, the caller is blocked until the message can be accepted fully on the child pipe.

This is pretty unfortunate, but it is indeed a consequence of nanomsg's design.  The NN_DONTWAIT flag refers, as I indicated, to waiting for an available pipe -- once we have one, we do "block" (not in kernel mode though) waiting for the send to complete.

(Note that critically the non-blocking I/O performed under the hood means that other streams and activity can take place, even though the calling thread is blocked.)

The nng library does buffer this, and returns to the caller immediately if asynchronous delivery is requested.  It also returns to the caller immediately once it has queued the message for delivery.

I'm closing this against "nanomsg" because we won't -- we can't -- "fix it".

**Closed by gdamore** 2017-10-13 06:43 UTC
