### ISSUE TITLE
nanocat: doesn't print anything with a short --interval

### ISSUE THREAD

**Issue by kristianlm** [nanomsg/nanomsg#376] opened 2015-03-03 13:13 UTC
This may actually belong to discussion on a mailing list, but here we go. I find this behaviour surprising. If I do req-rep request with--interval 0, nothing get's printed. I've got a "server" running with:

```bash
10 $ nanocat --rep --bind "tcp://0.0.0.0:12000" -D "hello world" -Q &
```

As I reduce the interval of the requests, the bandwidth (or rather, the frequency of the "hello world" printouts), increases like expected:

```bash
100 $ nanocat --req --connect "tcp://192.168.0.216:12000" -D "hello who" -Q -i 0.1 | pv >/dev/null
174 B 0:00:04 [ 139 B/s]

101 $ nanocat --req --connect "tcp://192.168.0.216:12000" -D "hello who" -Q -i 0.01 | pv >/dev/null
1.3KiB 0:00:21 [1.35KiB/s]

102 $ nanocat --req --connect "tcp://192.168.0.216:12000" -D "hello who" -Q -i 0.001 | pv >/dev/null
0 B 0:00:08 [   0 B/s]

103 $ nanocat --req --connect "tcp://192.168.0.216:12000" -D "hello who" -Q -i 0
0 B 0:00:08 [   0 B/s] 
```

As expected, `101` has more data coming out of it than `100`. [pv](http://www.ivarch.com/programs/pv.shtml) is just used to measure data volume on stdout.
 
When the interval gets really short, nanocat no longer prints anything. The server is getting the requests, my terminal from `10` is flooded with incoming requess. However, `103` never prints anything, neither does `102`.

Is this a bug or am I missing something?

**Comment by gdamore** [comment] 2015-06-01 03:38
If the interval is too short, you'll wind up with a value that is too short for the request to be serviced, and the pending request is canceled.

To be clear, the interval is  the interval used between requests, *not* the time between receiving a reply and sending the next request.

The code is pretty clear, in that this seems to be the intended behavior.  We could change it to a different semantic, and maybe that would be a good thing -- although if you want to say "do this twice a second", then the current semantic works, but the semantic of waiting until the reply is received would *not* work, since with retries and all it could take several more seconds!

Anyway, I'm closing this as not a bug for now.  Perhaps the documentation here can be made clearer.

**Closed by gdamore** 2015-06-01 03:38 UTC

**Comment by kristianlm** [comment] 2015-06-09 09:30
Oh, that makes sense. I was trying to experiment with nanomsg to measure performance for fun. So I wanted to say "don't wait between sending requests" and I misunderstood the semantics. I'll make my own client in C to measure throughput.

Thanks!
