### ISSUE TITLE
nn_send silently drops message if socket is not yet connected

### ISSUE THREAD

**Issue by vl409** [nanomsg/nanomsg#878] opened 2017-04-26 15:16 UTC
The example code and strace from 2 runs are below.

What happens is that when nn_send() is called, socket is not yet in connected state. 
The result is that underlying sendmsg() is not called, but no error is produced.
From a programmer's point of view, it is not clear - is socket in blocking mode or no?
If first, I'd expect that nn_connect() not return until really connected.
Otherwise, I'd expect nn_send returning me some kind of EAGAIN.
What is worse, it does not look like API provides any way to get state of socket.
I've also tried to look at socket stats, and the result is that 
befor calling nn_send() NN_STAT_CURRENT_CONNECTIONS is 1 for good case and zero for bad case.

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include <nanomsg/nn.h>
#include <nanomsg/survey.h>

int main()
{
    char  buf[100];

    int  s, rc, responses;

    s = nn_socket(AF_SP, NN_SURVEYOR);
    if (s == -1) {
        exit(1);
    }

    rc = nn_connect(s, "tcp://127.0.0.1:6666");
    if (rc == -1) {
        exit(1);
    }

    /* uncomment for nn_send() to succeed */
    //sleep(1);

    responses = 0;

    /* socket s not yet connected */
    rc = nn_send(s, "What service do you provide?", 29, 0);
    if (rc == -1) {
        exit(1);
    }

    printf("nn_send returned:%d\n", rc);

    while (1) {
        rc = nn_recv(s, buf, sizeof (buf), 0);

        if (rc < 0) {
            /* timedout */
            break;
        }

        responses++;
    }

    printf("survey complete, responses=%d\n", responses);

    return 0;
}

```
strace for bad case:
```
execve("./bs", ["./bs"], [/* 52 vars */]) = 0
brk(NULL)                               = 0x602000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3907d38000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=304075, ...}) = 0
mmap(NULL, 304075, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f3907ced000
close(3)                                = 0
open("/usr/lib64/libnanomsg.so.5.0.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\375\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=311864, ...}) = 0
mmap(NULL, 2366120, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f39078d5000
mprotect(0x7f3907913000, 2097152, PROT_NONE) = 0
mmap(0x7f3907b13000, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3e000) = 0x7f3907b13000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0002\10\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1917256, ...}) = 0
mmap(NULL, 3741976, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f3907543000
mprotect(0x7f39076cc000, 2093056, PROT_NONE) = 0
mmap(0x7f39078cb000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x188000) = 0x7f39078cb000
mmap(0x7f39078d1000, 14616, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f39078d1000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3907cec000
open("/lib64/libanl.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20\17\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=19584, ...}) = 0
mmap(NULL, 2109928, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f390733f000
mprotect(0x7f3907342000, 2093056, PROT_NONE) = 0
mmap(0x7f3907541000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f3907541000
close(3)                                = 0
open("/lib64/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P!\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=39264, ...}) = 0
mmap(NULL, 2124736, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f3907138000
mprotect(0x7f390713e000, 2093056, PROT_NONE) = 0
mmap(0x7f390733d000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5000) = 0x7f390733d000
close(3)                                = 0
open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\202`\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=138040, ...}) = 0
mmap(NULL, 2204744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f3906f1d000
mprotect(0x7f3906f33000, 2093056, PROT_NONE) = 0
mmap(0x7f3907132000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x7f3907132000
mmap(0x7f3907134000, 13384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f3907134000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3907ceb000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3907cea000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3907ce9000
arch_prctl(ARCH_SET_FS, 0x7f3907cea700) = 0
mprotect(0x7f39078cb000, 16384, PROT_READ) = 0
mprotect(0x7f3907132000, 4096, PROT_READ) = 0
mprotect(0x7f390733d000, 4096, PROT_READ) = 0
mprotect(0x7f3907541000, 4096, PROT_READ) = 0
mprotect(0x7f3907b13000, 8192, PROT_READ) = 0
mprotect(0x600000, 4096, PROT_READ)     = 0
mprotect(0x7f3907d39000, 4096, PROT_READ) = 0
munmap(0x7f3907ced000, 304075)          = 0
set_tid_address(0x7f3907cea9d0)         = 16882
set_robust_list(0x7f3907cea9e0, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7f3906f22b74, [], SA_RESTORER|SA_SIGINFO, 0x7f3906f2d660}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f3906f22bec, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f3906f2d660}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
futex(0x7f3907b16780, FUTEX_WAKE_PRIVATE, 2147483647) = 0
brk(NULL)                               = 0x602000
brk(0x624000)                           = 0x624000
eventfd2(0, EFD_CLOEXEC)                = 3
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
epoll_create1(EPOLL_CLOEXEC)            = 4
epoll_ctl(4, EPOLL_CTL_ADD, 3, {0, {u32=129067440, u64=139882918930864}}) = 0
epoll_ctl(4, EPOLL_CTL_MOD, 3, {EPOLLIN, {u32=129067440, u64=139882918930864}}) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f390671c000
mprotect(0x7f390671c000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f3906f1bff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f3906f1c9d0, tls=0x7f3906f1c700, child_tidptr=0x7f3906f1c9d0) = 16883
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
eventfd2(0, EFD_CLOEXEC)                = 5
fcntl(5, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(5, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
eventfd2(0, EFD_CLOEXEC)                = 6
fcntl(6, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(6, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
write(6, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_IP) = 7
fcntl(7, F_SETFD, FD_CLOEXEC)           = 0
fcntl(7, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(7, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
setsockopt(7, SOL_SOCKET, SO_SNDBUF, [131072], 4) = 0
setsockopt(7, SOL_SOCKET, SO_RCVBUF, [131072], 4) = 0
setsockopt(7, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(7, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
connect(7, {sa_family=AF_INET, sin_port=htons(6666), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
read(6, "\1\0\0\0\0\0\0\0", 8)          = 8
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 44), ...}) = 0
write(1, "nn_send returned:29\n", 20)   = 20
futex(0x6035b8, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x6035b8, FUTEX_WAKE_PRIVATE, 1)  = 0
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 1 ([{fd=6, revents=POLLIN}])
poll([{fd=6, events=POLLIN}], 1, 0)     = 1 ([{fd=6, revents=POLLIN}])
write(1, "survey complete, responses=0\n", 29) = 29
exit_group(0)                           = ?
+++ exited with 0 +++
```
strace for good case (with sleep):
```
execve("./bs", ["./bs"], [/* 52 vars */]) = 0
brk(NULL)                               = 0x602000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0b1e034000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=304075, ...}) = 0
mmap(NULL, 304075, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f0b1dfe9000
close(3)                                = 0
open("/usr/lib64/libnanomsg.so.5.0.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\375\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=311864, ...}) = 0
mmap(NULL, 2366120, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b1dbd1000
mprotect(0x7f0b1dc0f000, 2097152, PROT_NONE) = 0
mmap(0x7f0b1de0f000, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3e000) = 0x7f0b1de0f000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0002\10\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1917256, ...}) = 0
mmap(NULL, 3741976, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b1d83f000
mprotect(0x7f0b1d9c8000, 2093056, PROT_NONE) = 0
mmap(0x7f0b1dbc7000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x188000) = 0x7f0b1dbc7000
mmap(0x7f0b1dbcd000, 14616, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0b1dbcd000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0b1dfe8000
open("/lib64/libanl.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20\17\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=19584, ...}) = 0
mmap(NULL, 2109928, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b1d63b000
mprotect(0x7f0b1d63e000, 2093056, PROT_NONE) = 0
mmap(0x7f0b1d83d000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f0b1d83d000
close(3)                                = 0
open("/lib64/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P!\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=39264, ...}) = 0
mmap(NULL, 2124736, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b1d434000
mprotect(0x7f0b1d43a000, 2093056, PROT_NONE) = 0
mmap(0x7f0b1d639000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5000) = 0x7f0b1d639000
close(3)                                = 0
open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\202`\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=138040, ...}) = 0
mmap(NULL, 2204744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b1d219000
mprotect(0x7f0b1d22f000, 2093056, PROT_NONE) = 0
mmap(0x7f0b1d42e000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x7f0b1d42e000
mmap(0x7f0b1d430000, 13384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0b1d430000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0b1dfe7000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0b1dfe6000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0b1dfe5000
arch_prctl(ARCH_SET_FS, 0x7f0b1dfe6700) = 0
mprotect(0x7f0b1dbc7000, 16384, PROT_READ) = 0
mprotect(0x7f0b1d42e000, 4096, PROT_READ) = 0
mprotect(0x7f0b1d639000, 4096, PROT_READ) = 0
mprotect(0x7f0b1d83d000, 4096, PROT_READ) = 0
mprotect(0x7f0b1de0f000, 8192, PROT_READ) = 0
mprotect(0x600000, 4096, PROT_READ)     = 0
mprotect(0x7f0b1e035000, 4096, PROT_READ) = 0
munmap(0x7f0b1dfe9000, 304075)          = 0
set_tid_address(0x7f0b1dfe69d0)         = 16922
set_robust_list(0x7f0b1dfe69e0, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7f0b1d21eb74, [], SA_RESTORER|SA_SIGINFO, 0x7f0b1d229660}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f0b1d21ebec, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f0b1d229660}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
futex(0x7f0b1de12780, FUTEX_WAKE_PRIVATE, 2147483647) = 0
brk(NULL)                               = 0x602000
brk(0x624000)                           = 0x624000
eventfd2(0, EFD_CLOEXEC)                = 3
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
epoll_create1(EPOLL_CLOEXEC)            = 4
epoll_ctl(4, EPOLL_CTL_ADD, 3, {0, {u32=501295536, u64=139685722663344}}) = 0
epoll_ctl(4, EPOLL_CTL_MOD, 3, {EPOLLIN, {u32=501295536, u64=139685722663344}}) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f0b1ca18000
mprotect(0x7f0b1ca18000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f0b1d217ff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f0b1d2189d0, tls=0x7f0b1d218700, child_tidptr=0x7f0b1d2189d0) = 16923
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
eventfd2(0, EFD_CLOEXEC)                = 5
fcntl(5, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(5, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
eventfd2(0, EFD_CLOEXEC)                = 6
fcntl(6, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(6, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
write(6, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_IP) = 7
fcntl(7, F_SETFD, FD_CLOEXEC)           = 0
fcntl(7, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(7, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
setsockopt(7, SOL_SOCKET, SO_SNDBUF, [131072], 4) = 0
setsockopt(7, SOL_SOCKET, SO_RCVBUF, [131072], 4) = 0
setsockopt(7, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(7, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
connect(7, {sa_family=AF_INET, sin_port=htons(6666), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
nanosleep({1, 0}, 0x7ffc25a8f240)       = 0
sendmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\0\0\0\0\0\0\0!", iov_len=8}, {iov_base="\362O\237\241", iov_len=4}, {iov_base="What service do you provide?\0", iov_len=29}], msg_iovlen=3, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 41
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
read(6, "\1\0\0\0\0\0\0\0", 8)          = 8
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 44), ...}) = 0
write(1, "nn_send returned:29\n", 20)   = 20
poll([{fd=6, events=POLLIN}], 1, 100)   = 1 ([{fd=6, revents=POLLIN}])
poll([{fd=6, events=POLLIN}], 1, 0)     = 1 ([{fd=6, revents=POLLIN}])
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
read(6, "\1\0\0\0\0\0\0\0", 8)          = 8
futex(0x6035b8, FUTEX_WAKE_PRIVATE, 1)  = 1
poll([{fd=6, events=POLLIN}], 1, 100)   = 1 ([{fd=6, revents=POLLIN}])
poll([{fd=6, events=POLLIN}], 1, 0)     = 1 ([{fd=6, revents=POLLIN}])
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0x7f0b1de127e0, FUTEX_WAKE_PRIVATE, 1) = 1
read(6, "\1\0\0\0\0\0\0\0", 8)          = 8
futex(0x6035b8, FUTEX_WAKE_PRIVATE, 1)  = 1
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 0 (Timeout)
poll([{fd=6, events=POLLIN}], 1, 100)   = 1 ([{fd=6, revents=POLLIN}])
poll([{fd=6, events=POLLIN}], 1, 0)     = 1 ([{fd=6, revents=POLLIN}])
write(1, "survey complete, responses=2\n", 29) = 29
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by gdamore** [comment] 2017-04-26 22:08
Whether the message is dropped or not depends on the protocol.

With most of the protocols we just drop the message.   For example, a survey is taken based on who is connected.  It is in fact at some level a report of which peers exist and are ready.  Blocking would be a poor choice here (actually true for pretty much any of the multicast protocols.)  (Recall SURVEYOR can have multiple peer respondents!)

The state of underlying physical connections is specifically abstracted away from the application in nanomsg.  If this behavior isn't what you want, you probably don't actually want to use nanomsg; this is one of the differentiating features of nanomsg.

So, this is not a bug, but quite intentional behavior.

**Comment by vl409** [comment] 2017-04-27 06:27
ok, this makes sense. I suspected something like that, given the fact that there indeed can be anything behind the scenes of socket interface. It is true that messages can be lost at any point (before or after leaving host) and you have to live with this and program retransmits or whatever. 
But why ignore local errors? It is strange to expect something to happen if you even failed to send something to network (or at least pass it to the operating system's socket buffer).
With survey, this means almost always doubling timeout, since you don't retry until you realized that no response arrived in deadline interval.

**Comment by gdamore** [comment] 2017-05-11 15:56
The rationale here is that the application shouldn't have to double timeouts or anything like that; the intention is to free applications from having to worry about this.  This means that apps that need guaranteed delivery should use REQ/REP and rely on the REQ to resend (and they really need to use idempotent REQ messages too!)

Under the hood, the reliable patterns (REQ/REP, and to a lesser extent PIPELINE) actually queue messages and if they cannot be delivered to a peer (because no peer exists) will hold them until a peer becomes available.   So again, no doubling needed.

This is a design trade-off.  With normal sockets, you have to handle them all in your app; nanomsg's design center is to free the application from all these various concerns.

**Comment by gdamore** [comment] 2017-05-12 20:29
I think I've answered this now, closing it.

**Closed by gdamore** 2017-05-12 20:29 UTC
