### ISSUE TITLE
Unexpected source: state=5 source=1 action=5 for REQ/REP and NN_RCVMAXSIZE

### ISSUE THREAD

**Issue by lucasb-eyer** [nanomsg/nanomsg#607] opened 2016-02-21 13:54 UTC
Whenever a `REP` sends a message to a `REQ`, if the message is larger than the `REQ`'s `NN_RCVMAXSIZE` option, the `REP` dies with the following message:

```
Unexpected source: state=5 source=1 action=5 (src/transports/utils/streamhdr.c:306)
fish: Job 1, “python monitor_srv.py” terminated by signal SIGABRT (Abort)
```

Is this intended behaviour? It means that any `REQ` can kill a `REP` server very easily. I'm using the `nnpy` wrapper and didn't try to reproduce it in C. Here is the minimal case which I could write to reliably reproduce this:

- `bug-srv.py`:

```
import nnpy
import time

rep = nnpy.Socket(nnpy.AF_SP, nnpy.REP)
rep.bind("tcp://127.0.0.1:12345")
foo = rep.recv()
print(foo)
bar = b"0"*1024*1025
rep.send(bar)
print("sent")
time.sleep(10)
rep.close()
```

- `bug-cli.py`

```
import nnpy

req = nnpy.Socket(nnpy.AF_SP, nnpy.REQ)
req.connect("tcp://127.0.0.1:12345")
req.send(b"foo")
print("sent")
bar = req.recv()
print(bar)
req.close()
```

Usage:

```
$ python bug-srv.py
b'foo'
sent
Unexpected source: state=5 source=1 action=5 (src/transports/utils/streamhdr.c:306)
fish: Job 1, “python bug-srv.py ” terminated by signal SIGABRT (Abort)
```

```
$ python bug-cli.py
sent
```

Interestingly, while trying to reproduce it, I once got a different message from `bug-srv.py`, not sure if this helps or distracts:

```
Assertion failed: self->next == NN_QUEUE_NOTINQUEUE (src/utils/queue.c:102)
fish: Job 1, “python bug-srv.py ” terminated by signal SIGABRT (Abort)
```

**Comment by gdamore** [comment] 2016-02-22 04:41
Looks like a bug to me.

**Comment by JackDunaway** [comment] 2016-04-13 02:13
Based on the abort being thrown on line 306, this appears to be an older version of libnanomsg. 1) We should look into getting the Python language bindings up to date, and 2) see if we can't upgrade the assertion helper macros (e.g., https://github.com/nanomsg/nanomsg/blob/master/src/utils/err.h#L48-L49) to include the libnanomsg library version.

@lucasb-eyer, can you confirm which Python binding you're using, so we can see about bringing it up to date with libnanomsg? Thank you!

**Comment by gdamore** [comment] 2016-04-21 22:32
I'm pretty sure this is indeed fixed by c0e92dd84f0263fb4f2ad504dd7ccbdf42a24c21
I'm going to close it.  If it crops up again in HEAD or 0.9 (after 0.9 is released) please let us know.

**Closed by gdamore** 2016-04-21 22:32 UTC

**Comment by lucasb-eyer** [comment] 2016-04-21 22:35
Sorry, currently too busy with other things. I'll indeed let you know in the future if it still happens, thanks for the feedback!

**Comment by lucasb-eyer** [comment] 2016-04-24 12:45
It indeed seems fixed in HEAD. I was using the `nnpy` bindings, sorry for having missed that question.

**Comment by gdamore** [comment] 2016-04-24 15:16
Glad that is confirmed.
